<?php

/**
 * L8M
 *
 *
 * @filesource /application/views/scripts/dates/index.phtml
 * @author     Krishna Bhatt <krishna.patel@bcssarl.com>
 * @version    $Id: index.phtml 63 2018-12-03 05:25:59Z nm $
 */
$this->layout()->title = $this->translate('Termine', 'de');
$this->layout()->headline = $this->translate('Termine', 'de');
echo $this->protocolListPage($this->datesCollection, $this->datesPager);