<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/admin/views/scripts/otc/create.phtml
 * @author     Krishna Bhatt <krishna.patel@bcssarl.com>
 * @version    $Id: create.phtml 7 2019-01-08 10:36:38Z nm $
 */

if (isset($this->modelForm)) {
	echo $this->modelForm;
}

$this->headScript()->captureStart();
?>

$(document).ready(function() {
	$('li#otc_relation_m2n_otcm2ndepartment_selector_link_5_li').click();
	$('a.otc_relation_m2n_otcm2ndepartment_add').click();
});

<?php
$this->headScript()->captureEnd();