<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/admin/views/scripts/brand/edit.phtml
 * @author     Pritam Parmar <pritam.parmar@bcssarl.com>
 * @version    $Id: edit.phtml 7 2019-06-28 11:52:00Z pp $
 */

if (isset($this->modelModelColumn) &&
	isset($this->modelModelName)) {

	$modelName = $this->modelModelColumn . ' <strong>' . $this->modelModelName . '</strong> (ID: ' . $this->modelModelId . ')';
} else {
	$modelName = 'ID: ' . $this->modelModelId;
}

?>
<p><?php echo $this->translate('You are editing')?>: <?php echo $modelName; ?></p>
<?php

if (isset($this->modelForm)) {
	echo $this->modelForm;
}