<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/admin/views/scripts/user/create.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: create.phtml 7 2014-03-11 16:18:40Z nm $
 */
$this->headStyle()->captureStart();
?>
/* hide the unused field of brand
.selecte_tab .relation-value table tr:not(:first-child){display:none;}
 hide the parent and super parent
#entity_form #entity_parent_user_id-label, #entity_form #entity_parent_user_id-element   { display:none;}
#entity_form #entity_super_parent_id-label, #entity_form #entity_super_parent_id-element { display:none;} */
<?php
$this->headStyle()->captureEnd();

if (isset($this->modelForm)) {
	echo $this->modelForm;
}

$this->headScript()->captureStart();
?>

$(document).ready(function() {
    var parent_span = $('li#entity_parent_user_id_selected_id span').text();
    if(parent_span != ''){
        $('#entity_department_id-label').hide();
        $('#entity_department_id').hide();
        $('#entity_contract_type_id-label').hide();
        $('#entity_contract_type_id').hide();
        $('#entity_region_id-label').hide();
        $('#entity_region_id').hide();
        $('#entity_relation_m2n_entitym2nbrandoptionmodel-label').hide();
        $('#entity_relation_m2n_entitym2nbrandoptionmodel-element').hide();
    }

	$('#entity_relation_m2n_entitym2nbrand-label').remove();
	$('#entity_relation_m2n_entitym2nbrand-element').remove();
	$("li.relation-value input[type=text]").each(function () {
		var val = $(this).val();
		if(val == ""){
			$(this).val(0);
		}
	});
	$('#entity_relation_m2n_entitym2nbrandoptionmodel-element .relation-values .add').remove();
	$(".entity_relation_m2n_entitym2nbrandoptionmodel_add").click(function(){
		$("li.relation-value input[type=text]").each(function () {
			var val = $(this).val();
			if(val == ""){
				$(this).val(0);
			}
		});
		$('#entity_relation_m2n_entitym2nbrandoptionmodel-element .relation-values .add').remove();
	});
	$('.selected-values').on('keypress', 'input[type=text]', function(e){
		//if the letter is not digit then display error and don't type anything
		if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57 || e.which == 46)) {
				return false;
		}
	});
	$('.selected-values').on('input', 'input[type=text]', function(e){
		if($(this).val()==""){
			$(this).val(0);
		}
    });

    $('.entity_parent_user_id_add').on('click', function() {
        var parent_span = $('li#entity_parent_user_id_selected_id span').text();
        if(parent_span != ''){
            $('#entity_department_id-label').hide();
            $('#entity_department_id').hide();
            $('#entity_contract_type_id-label').hide();
            $('#entity_contract_type_id').hide();
            $('#entity_region_id-label').hide();
            $('#entity_region_id').hide();
            $('#entity_relation_m2n_entitym2nbrandoptionmodel-label').hide();
            $('#entity_relation_m2n_entitym2nbrandoptionmodel-element').hide();
        }
    });


    $(document).on('click', '#entity_parent_user_id_selected', function() {
        $('#entity_department_id-label').show();
        $('#entity_department_id').show();
        $('#entity_contract_type_id-label').show();
        $('#entity_contract_type_id').show();
        $('#entity_region_id-label').show();
        $('#entity_region_id').show();
        $('#entity_relation_m2n_entitym2nbrandoptionmodel-label').show();
        $('#entity_relation_m2n_entitym2nbrandoptionmodel-element').show();
    });

});


<?php
$this->headScript()->captureEnd();
