<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/admin/views/scripts/user/edit.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: edit.phtml 7 2014-03-11 16:18:40Z nm $
 */
$this->headStyle()->captureStart();
?>
/* hide the unused filed of brand*/
.selecte_tab .relation-value table tr:not(:first-child){display:none;}
/* hide the parent and super parent */
#entity_form #entity_parent_user_id-label, #entity_form #entity_parent_user_id-element   { display:none;}
#entity_form #entity_super_parent_id-label, #entity_form #entity_super_parent_id-element { display:none;}
<?php
$this->headStyle()->captureEnd();

if (isset($this->modelModelColumn) &&
	isset($this->modelModelName)) {

	$modelName = $this->modelModelColumn . ' <strong>' . $this->modelModelName . '</strong> (ID: ' . $this->modelModelId . ')';
} else {
	$modelName = 'ID: ' . $this->modelModelId;
}

?>
<p><?php echo $this->translate('You are editing')?>: <?php echo $modelName; ?></p>
<?php

if (isset($this->modelForm)) {
	echo $this->modelForm;
}

$this->headScript()->captureStart();
?>

$(document).ready(function() {
	$('#entity_relation_m2n_entitym2nbrand-label').remove();
	$('#entity_relation_m2n_entitym2nbrand-element').remove();

	$("li.relation-value input[type=text]").each(function () {
		var val = $(this).val();
		if(val == ""){
			$(this).val(0);
		}
	});
	$('#entity_relation_m2n_entitym2nbrandoptionmodel-element .relation-values .add').remove();
	$(".entity_relation_m2n_entitym2nbrandoptionmodel_add").click(function(){
		$("li.relation-value input[type=text]").each(function () {
			var val = $(this).val();
			if(val == ""){
				$(this).val(0);
			}
		});
		$('#entity_relation_m2n_entitym2nbrandoptionmodel-element .relation-values .add').remove();
	});
	$('.selected-values').on('keypress', 'input[type=text]', function(e){
		//if the letter is not digit then display error and don't type anything
		if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57 || e.which == 46)) {
				return false;
		}
	});
	$('.selected-values').on('input', 'input[type=text]', function(e){
		if($(this).val()==""){
			$(this).val(0);
		}
	});
});

<?php
$this->headScript()->captureEnd();
?>
<script>
$(document).ready(function() {
var brands = <?php echo json_encode($this->brands);  ?>;
	var brandOptionId;
	var chkName;
	$.each( brands, function( key, value ) {
		brandOptionId = 'entity_relation_m2n_entitym2nbrandoptionmodel_selector_link_' + value + '_li';
		chkName = 'entity_relation_m2n_entitym2nbrandoptionmodel_' + value + '_selected_id';
		$('#'+brandOptionId).trigger('click');
		$('.entity_relation_m2n_entitym2nbrandoptionmodel_add').trigger('click');
		if(!$("#"+chkName+" input:checkbox").prop("checked")){
			$("#"+chkName+" input:checkbox").trigger('click');
		}
	});
});
</script>
