<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/admin/views/scripts/index/index.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: index.phtml 7 2014-03-11 16:18:40Z nm $
 */



echo '<p>' . $this->translate('Choose, what to administrate.') . '</p>';

if (isset($this->backendInfo) &&
	$this->backendInfo) {

	ob_start();

?>
<ul class="iconized">
	<li class="information"><?php echo $this->backendInfo; ?></li>
</ul>
<?php

	echo $this->box(ob_get_clean(), 'bigger min-height-zero');
	echo $this->box('', '', 'display:none;');
}

/**
 * boxes
 */
foreach ($this->blankSystemMenuStructure() as $menuBox) {
	$contentBox = NULL;

	foreach ($menuBox['links'] as $menuBoxLink) {
		if (!isset($menuBoxLink['showOnlyInEnvironment'])) {
			$contentBox .= '<li class="' . $menuBoxLink['css'] . '"><a href="' . $menuBoxLink['link'] . '">' . $menuBoxLink['name'] . '</a></li>';
		} else
		if (isset($menuBoxLink['showOnlyInEnvironment']) &&
			$menuBoxLink['showOnlyInEnvironment'] == L8M_Environment::getInstance()->getEnvironment()) {

			$contentBox .= '<li class="' . $menuBoxLink['css'] . '"><a href="' . $menuBoxLink['link'] . '">' . $menuBoxLink['name'] . '</a></li>';
		}
	}

	if ($contentBox) {
		$contentBox = '<ul class="iconized">' . $contentBox . '</ul>';
	}

	if ($menuBox['description']) {
		$contentBox = '<p class="description">' . $menuBox['description'] . '</p>' . $contentBox;
	}

	if ($contentBox) {
		$contentBox = '<h3>' . $menuBox['title'] . '</h3>' . $contentBox;
		echo $this->box($contentBox);
	}
}