<?php

/**
 * L8M
 *
 *
 * @filesource /application/models/CountryZone/Import.php
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: Import.php 506 2016-07-21 12:16:02Z nm $
 */

/**
 *
 *
 * Default_Model_CountryZone_Import
 *
 *
 */
class Default_Model_CountryZone_Import extends L8M_Doctrine_Import_Abstract
{

	/**
	 *
	 *
	 * Class Methods
	 *
	 *
	 */

	/**
	 * Initializes instance.
	 *
	 * @return void
	 */
	protected function _init()
	{
		parent::_init();

		$array = array(
			array('id'=>1,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Alabama','name_en'=>null,'name_de'=>null),
			array('id'=>2,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Alaska','name_en'=>null,'name_de'=>null),
			array('id'=>4,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Arizona','name_en'=>null,'name_de'=>null),
			array('id'=>5,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Arkansas','name_en'=>null,'name_de'=>null),
			array('id'=>12,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'California','name_en'=>null,'name_de'=>null),
			array('id'=>13,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Colorado','name_en'=>null,'name_de'=>null),
			array('id'=>14,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Connecticut','name_en'=>null,'name_de'=>null),
			array('id'=>15,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Delaware','name_en'=>null,'name_de'=>null),
			array('id'=>16,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'District of Columbia','name_en'=>null,'name_de'=>null),
			array('id'=>18,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Florida','name_en'=>null,'name_de'=>null),
			array('id'=>19,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Georgia','name_en'=>null,'name_de'=>null),
			array('id'=>20,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Guam','name_en'=>null,'name_de'=>null),
			array('id'=>21,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Hawaii','name_en'=>null,'name_de'=>null),
			array('id'=>22,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Idaho','name_en'=>null,'name_de'=>null),
			array('id'=>23,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Illinois','name_en'=>null,'name_de'=>null),
			array('id'=>24,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Indiana','name_en'=>null,'name_de'=>null),
			array('id'=>25,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Iowa','name_en'=>null,'name_de'=>null),
			array('id'=>26,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Kansas','name_en'=>null,'name_de'=>null),
			array('id'=>27,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Kentucky','name_en'=>null,'name_de'=>null),
			array('id'=>28,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Louisiana','name_en'=>null,'name_de'=>null),
			array('id'=>29,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Maine','name_en'=>null,'name_de'=>null),
			array('id'=>31,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Maryland','name_en'=>null,'name_de'=>null),
			array('id'=>32,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Massachusetts','name_en'=>null,'name_de'=>null),
			array('id'=>33,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Michigan','name_en'=>null,'name_de'=>null),
			array('id'=>34,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Minnesota','name_en'=>null,'name_de'=>null),
			array('id'=>35,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Mississippi','name_en'=>null,'name_de'=>null),
			array('id'=>36,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Missouri','name_en'=>null,'name_de'=>null),
			array('id'=>37,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Montana','name_en'=>null,'name_de'=>null),
			array('id'=>38,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Nebraska','name_en'=>null,'name_de'=>null),
			array('id'=>39,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Nevada','name_en'=>null,'name_de'=>null),
			array('id'=>40,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'New Hampshire','name_en'=>null,'name_de'=>null),
			array('id'=>41,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'New Jersey','name_en'=>null,'name_de'=>null),
			array('id'=>42,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'New Mexico','name_en'=>null,'name_de'=>null),
			array('id'=>43,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'New York','name_en'=>null,'name_de'=>null),
			array('id'=>44,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'North Carolina','name_en'=>null,'name_de'=>null),
			array('id'=>45,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'North Dakota','name_en'=>null,'name_de'=>null),
			array('id'=>47,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Ohio','name_en'=>null,'name_de'=>null),
			array('id'=>48,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Oklahoma','name_en'=>null,'name_de'=>null),
			array('id'=>49,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Oregon','name_en'=>null,'name_de'=>null),
			array('id'=>51,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Pennsylvania','name_en'=>null,'name_de'=>null),
			array('id'=>52,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Puerto Rico','name_en'=>null,'name_de'=>null),
			array('id'=>53,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Rhode Island','name_en'=>null,'name_de'=>null),
			array('id'=>54,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'South Carolina','name_en'=>null,'name_de'=>null),
			array('id'=>55,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'South Dakota','name_en'=>null,'name_de'=>null),
			array('id'=>56,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Tennessee','name_en'=>null,'name_de'=>null),
			array('id'=>57,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Texas','name_en'=>null,'name_de'=>null),
			array('id'=>58,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Utah','name_en'=>null,'name_de'=>null),
			array('id'=>59,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Vermont','name_en'=>null,'name_de'=>null),
			array('id'=>61,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Virginia','name_en'=>null,'name_de'=>null),
			array('id'=>62,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Washington','name_en'=>null,'name_de'=>null),
			array('id'=>63,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'West Virginia','name_en'=>null,'name_de'=>null),
			array('id'=>64,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Wisconsin','name_en'=>null,'name_de'=>null),
			array('id'=>65,'country_iso_3'=>'USA','zone_code'=>NULL,'name_local'=>'Wyoming','name_en'=>null,'name_de'=>null),
			array('id'=>66,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Alberta','name_en'=>null,'name_de'=>null),
			array('id'=>67,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'British Columbia','name_en'=>null,'name_de'=>null),
			array('id'=>68,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Manitoba','name_en'=>null,'name_de'=>null),
			array('id'=>69,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Newfoundland and Labrabor','name_en'=>null,'name_de'=>null),
			array('id'=>70,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'New Brunswick','name_en'=>null,'name_de'=>null),
			array('id'=>71,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Nova Scotia','name_en'=>null,'name_de'=>null),
			array('id'=>72,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Northwest Territories','name_en'=>null,'name_de'=>null),
			array('id'=>73,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Nunavut','name_en'=>null,'name_de'=>null),
			array('id'=>74,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Ontario','name_en'=>null,'name_de'=>null),
			array('id'=>75,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Prince Edward Island','name_en'=>null,'name_de'=>null),
			array('id'=>76,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Québec','name_en'=>'Quebec','name_de'=>null),
			array('id'=>77,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Saskatchewan','name_en'=>null,'name_de'=>null),
			array('id'=>78,'country_iso_3'=>'CAN','zone_code'=>NULL,'name_local'=>'Yukon Territory','name_en'=>null,'name_de'=>null),
			array('id'=>79,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Niedersachsen','name_en'=>'Lower Saxony','name_de'=>null),
			array('id'=>80,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Baden-Württemberg','name_en'=>null,'name_de'=>null),
			array('id'=>81,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Bayern','name_en'=>'Bavaria','name_de'=>null),
			array('id'=>82,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Berlin','name_en'=>null,'name_de'=>null),
			array('id'=>83,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Brandenburg','name_en'=>null,'name_de'=>null),
			array('id'=>84,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Bremen','name_en'=>null,'name_de'=>null),
			array('id'=>85,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Hamburg','name_en'=>null,'name_de'=>null),
			array('id'=>86,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Hessen','name_en'=>'Hesse','name_de'=>null),
			array('id'=>87,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Mecklenburg-Vorpommern','name_en'=>null,'name_de'=>null),
			array('id'=>88,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Nordrhein-Westfalen','name_en'=>'North Rhine-Westphalia','name_de'=>null),
			array('id'=>89,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Rheinland-Pfalz','name_en'=>'Rhineland-Palatinate','name_de'=>null),
			array('id'=>90,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Saarland','name_en'=>null,'name_de'=>null),
			array('id'=>91,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Sachsen','name_en'=>'Saxony','name_de'=>null),
			array('id'=>92,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Sachsen-Anhalt','name_en'=>'Saxony-Anhalt','name_de'=>null),
			array('id'=>93,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Schleswig-Holstein','name_en'=>null,'name_de'=>null),
			array('id'=>94,'country_iso_3'=>'DEU','zone_code'=>NULL,'name_local'=>'Thüringen','name_en'=>'Thuringia','name_de'=>null),
			array('id'=>95,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Wien','name_en'=>'Vienna','name_de'=>null),
			array('id'=>96,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Niederösterreich','name_en'=>'Lower Austria','name_de'=>null),
			array('id'=>97,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Oberösterreich','name_en'=>'Upper Austria','name_de'=>null),
			array('id'=>98,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Salzburg','name_en'=>null,'name_de'=>null),
			array('id'=>99,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Kärnten','name_en'=>'Carinthia','name_de'=>null),
			array('id'=>100,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Steiermark','name_en'=>'Styria','name_de'=>null),
			array('id'=>101,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Tirol','name_en'=>'Tyrol','name_de'=>null),
			array('id'=>102,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Burgenland','name_en'=>null,'name_de'=>null),
			array('id'=>103,'country_iso_3'=>'AUT','zone_code'=>NULL,'name_local'=>'Vorarlberg','name_en'=>null,'name_de'=>null),
			array('id'=>104,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Aargau','name_en'=>null,'name_de'=>null),
			array('id'=>105,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Appenzell Innerrhoden','name_en'=>null,'name_de'=>null),
			array('id'=>106,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Appenzell Ausserrhoden','name_en'=>null,'name_de'=>null),
			array('id'=>107,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Bern','name_en'=>null,'name_de'=>null),
			array('id'=>108,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Basel-Landschaft','name_en'=>null,'name_de'=>null),
			array('id'=>109,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Basel-Stadt','name_en'=>null,'name_de'=>null),
			array('id'=>110,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Freiburg','name_en'=>null,'name_de'=>null),
			array('id'=>111,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Genf','name_en'=>'Geneve','name_de'=>null),
			array('id'=>112,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Glarus','name_en'=>null,'name_de'=>null),
			array('id'=>113,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Graubünden','name_en'=>null,'name_de'=>null),
			array('id'=>114,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Jura','name_en'=>null,'name_de'=>null),
			array('id'=>115,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Luzern','name_en'=>null,'name_de'=>null),
			array('id'=>116,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Neuenburg','name_en'=>null,'name_de'=>null),
			array('id'=>117,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Nidwalden','name_en'=>null,'name_de'=>null),
			array('id'=>118,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Obwalden','name_en'=>null,'name_de'=>null),
			array('id'=>119,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'St. Gallen','name_en'=>null,'name_de'=>null),
			array('id'=>120,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Schaffhausen','name_en'=>null,'name_de'=>null),
			array('id'=>121,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Solothurn','name_en'=>null,'name_de'=>null),
			array('id'=>122,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Schwyz','name_en'=>null,'name_de'=>null),
			array('id'=>123,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Thurgau','name_en'=>null,'name_de'=>null),
			array('id'=>124,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Tessin','name_en'=>null,'name_de'=>null),
			array('id'=>125,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Uri','name_en'=>null,'name_de'=>null),
			array('id'=>126,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Waadt','name_en'=>null,'name_de'=>null),
			array('id'=>127,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Wallis','name_en'=>null,'name_de'=>null),
			array('id'=>128,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Zug','name_en'=>null,'name_de'=>null),
			array('id'=>129,'country_iso_3'=>'CHE','zone_code'=>NULL,'name_local'=>'Zürich','name_en'=>null,'name_de'=>null),
			array('id'=>130,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Alava','name_en'=>null,'name_de'=>null),
			array('id'=>131,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Malaga','name_en'=>null,'name_de'=>null),
			array('id'=>132,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Segovia','name_en'=>null,'name_de'=>null),
			array('id'=>133,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Granada','name_en'=>null,'name_de'=>null),
			array('id'=>134,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Jaen','name_en'=>null,'name_de'=>null),
			array('id'=>135,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Sevilla','name_en'=>null,'name_de'=>null),
			array('id'=>136,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Barcelona','name_en'=>null,'name_de'=>null),
			array('id'=>137,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Valencia','name_en'=>null,'name_de'=>null),
			array('id'=>138,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Alicante','name_en'=>null,'name_de'=>null),
			array('id'=>139,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Almeria','name_en'=>null,'name_de'=>null),
			array('id'=>140,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Asturias','name_en'=>null,'name_de'=>null),
			array('id'=>141,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Avila','name_en'=>null,'name_de'=>null),
			array('id'=>142,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Badajoz','name_en'=>null,'name_de'=>null),
			array('id'=>143,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Burgos','name_en'=>null,'name_de'=>null),
			array('id'=>144,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Caceres','name_en'=>null,'name_de'=>null),
			array('id'=>145,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Cadiz','name_en'=>null,'name_de'=>null),
			array('id'=>146,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Cantabria','name_en'=>null,'name_de'=>null),
			array('id'=>147,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Castellon','name_en'=>null,'name_de'=>null),
			array('id'=>148,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Ceuta','name_en'=>null,'name_de'=>null),
			array('id'=>149,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Ciudad Real','name_en'=>null,'name_de'=>null),
			array('id'=>150,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Cordoba','name_en'=>null,'name_de'=>null),
			array('id'=>151,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Cuenca','name_en'=>null,'name_de'=>null),
			array('id'=>152,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Girona','name_en'=>null,'name_de'=>null),
			array('id'=>153,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Las Palmas','name_en'=>null,'name_de'=>null),
			array('id'=>154,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Guadalajara','name_en'=>null,'name_de'=>null),
			array('id'=>155,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Guipuzcoa','name_en'=>null,'name_de'=>null),
			array('id'=>156,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Huelva','name_en'=>null,'name_de'=>null),
			array('id'=>157,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Huesca','name_en'=>null,'name_de'=>null),
			array('id'=>158,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'A Coruña','name_en'=>null,'name_de'=>null),
			array('id'=>159,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'La Rioja','name_en'=>null,'name_de'=>null),
			array('id'=>160,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Leon','name_en'=>null,'name_de'=>null),
			array('id'=>161,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Lugo','name_en'=>null,'name_de'=>null),
			array('id'=>162,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Lleida','name_en'=>null,'name_de'=>null),
			array('id'=>163,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Madrid','name_en'=>null,'name_de'=>null),
			array('id'=>164,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Baleares','name_en'=>null,'name_de'=>null),
			array('id'=>166,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Murcia','name_en'=>null,'name_de'=>null),
			array('id'=>167,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Navarra','name_en'=>null,'name_de'=>null),
			array('id'=>168,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Ourense','name_en'=>null,'name_de'=>null),
			array('id'=>169,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Palencia','name_en'=>null,'name_de'=>null),
			array('id'=>170,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Pontevedra','name_en'=>null,'name_de'=>null),
			array('id'=>171,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Salamanca','name_en'=>null,'name_de'=>null),
			array('id'=>172,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Soria','name_en'=>null,'name_de'=>null),
			array('id'=>173,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Tarragona','name_en'=>null,'name_de'=>null),
			array('id'=>174,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Tenerife','name_en'=>null,'name_de'=>null),
			array('id'=>175,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Teruel','name_en'=>null,'name_de'=>null),
			array('id'=>176,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Toledo','name_en'=>null,'name_de'=>null),
			array('id'=>177,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Valladolid','name_en'=>null,'name_de'=>null),
			array('id'=>178,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Vizcaya','name_en'=>null,'name_de'=>null),
			array('id'=>179,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Zamora','name_en'=>null,'name_de'=>null),
			array('id'=>180,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Zaragoza','name_en'=>null,'name_de'=>null),
			array('id'=>181,'country_iso_3'=>'ESP','zone_code'=>NULL,'name_local'=>'Melilla','name_en'=>null,'name_de'=>null),
			array('id'=>182,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Aguascalientes','name_en'=>null,'name_de'=>null),
			array('id'=>183,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Baja California Sur','name_en'=>null,'name_de'=>null),
			array('id'=>184,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Baja California Norte','name_en'=>null,'name_de'=>null),
			array('id'=>185,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Campeche','name_en'=>null,'name_de'=>null),
			array('id'=>186,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Chiapas','name_en'=>null,'name_de'=>null),
			array('id'=>187,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Chihuahua','name_en'=>null,'name_de'=>null),
			array('id'=>188,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Coahuila','name_en'=>null,'name_de'=>null),
			array('id'=>189,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Colima','name_en'=>null,'name_de'=>null),
			array('id'=>190,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Distrito Federal','name_en'=>null,'name_de'=>null),
			array('id'=>191,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Durango','name_en'=>null,'name_de'=>null),
			array('id'=>192,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Guanajuato','name_en'=>null,'name_de'=>null),
			array('id'=>193,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Guerrero','name_en'=>null,'name_de'=>null),
			array('id'=>194,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Hidalgo','name_en'=>null,'name_de'=>null),
			array('id'=>195,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Jalisco','name_en'=>null,'name_de'=>null),
			array('id'=>196,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'México','name_en'=>null,'name_de'=>null),
			array('id'=>197,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Michoacán','name_en'=>null,'name_de'=>null),
			array('id'=>198,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Morelos','name_en'=>null,'name_de'=>null),
			array('id'=>199,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Nayarit','name_en'=>null,'name_de'=>null),
			array('id'=>200,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Nuevo León','name_en'=>null,'name_de'=>null),
			array('id'=>201,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Oaxaca','name_en'=>null,'name_de'=>null),
			array('id'=>202,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Puebla','name_en'=>null,'name_de'=>null),
			array('id'=>203,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Querétaro','name_en'=>null,'name_de'=>null),
			array('id'=>204,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Quintana Roo','name_en'=>null,'name_de'=>null),
			array('id'=>205,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'San Luis Potosí','name_en'=>null,'name_de'=>null),
			array('id'=>206,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Sinaloa','name_en'=>null,'name_de'=>null),
			array('id'=>207,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Sonora','name_en'=>null,'name_de'=>null),
			array('id'=>208,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Tabasco','name_en'=>null,'name_de'=>null),
			array('id'=>209,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Tamaulipas','name_en'=>null,'name_de'=>null),
			array('id'=>210,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Tlaxcala','name_en'=>null,'name_de'=>null),
			array('id'=>211,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Veracruz','name_en'=>null,'name_de'=>null),
			array('id'=>212,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Yucatán','name_en'=>null,'name_de'=>null),
			array('id'=>213,'country_iso_3'=>'MEX','zone_code'=>NULL,'name_local'=>'Zacatecas','name_en'=>null,'name_de'=>null),
			array('id'=>214,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'Australian Capital Territory','name_en'=>null,'name_de'=>null),
			array('id'=>215,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'New South Wales','name_en'=>null,'name_de'=>null),
			array('id'=>216,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'Northern Territory','name_en'=>null,'name_de'=>null),
			array('id'=>217,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'Queensland','name_en'=>null,'name_de'=>null),
			array('id'=>218,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'South Australia','name_en'=>null,'name_de'=>null),
			array('id'=>219,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'Tasmania','name_en'=>null,'name_de'=>null),
			array('id'=>220,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'Victoria','name_en'=>null,'name_de'=>null),
			array('id'=>221,'country_iso_3'=>'AUS','zone_code'=>NULL,'name_local'=>'Western Australia','name_en'=>null,'name_de'=>null),
			array('id'=>222,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Agrigento','name_en'=>null,'name_de'=>null),
			array('id'=>223,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Alessandria','name_en'=>null,'name_de'=>null),
			array('id'=>224,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Ancona','name_en'=>null,'name_de'=>null),
			array('id'=>225,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Aosta','name_en'=>null,'name_de'=>null),
			array('id'=>226,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Ascoli Piceno','name_en'=>null,'name_de'=>null),
			array('id'=>227,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'L\'Aquila','name_en'=>null,'name_de'=>null),
			array('id'=>228,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Arezzo','name_en'=>null,'name_de'=>null),
			array('id'=>229,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Asti','name_en'=>null,'name_de'=>null),
			array('id'=>230,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Avellino','name_en'=>null,'name_de'=>null),
			array('id'=>231,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Bari','name_en'=>null,'name_de'=>null),
			array('id'=>232,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Bergamo','name_en'=>null,'name_de'=>null),
			array('id'=>233,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Biella','name_en'=>null,'name_de'=>null),
			array('id'=>234,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Belluno','name_en'=>null,'name_de'=>null),
			array('id'=>235,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Benevento','name_en'=>null,'name_de'=>null),
			array('id'=>236,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Bologna','name_en'=>null,'name_de'=>null),
			array('id'=>237,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Brindisi','name_en'=>null,'name_de'=>null),
			array('id'=>238,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Brescia','name_en'=>null,'name_de'=>null),
			array('id'=>239,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Bolzano','name_en'=>null,'name_de'=>null),
			array('id'=>240,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Cagliari','name_en'=>null,'name_de'=>null),
			array('id'=>241,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Campobasso','name_en'=>null,'name_de'=>null),
			array('id'=>242,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Caserta','name_en'=>null,'name_de'=>null),
			array('id'=>243,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Chieti','name_en'=>null,'name_de'=>null),
			array('id'=>244,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Caltanissetta','name_en'=>null,'name_de'=>null),
			array('id'=>245,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Cuneo','name_en'=>null,'name_de'=>null),
			array('id'=>246,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Como','name_en'=>null,'name_de'=>null),
			array('id'=>247,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Cremona','name_en'=>null,'name_de'=>null),
			array('id'=>248,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Cosenza','name_en'=>null,'name_de'=>null),
			array('id'=>249,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Catania','name_en'=>null,'name_de'=>null),
			array('id'=>250,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Catanzaro','name_en'=>null,'name_de'=>null),
			array('id'=>251,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Enna','name_en'=>null,'name_de'=>null),
			array('id'=>252,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Ferrara','name_en'=>null,'name_de'=>null),
			array('id'=>253,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Foggia','name_en'=>null,'name_de'=>null),
			array('id'=>254,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Firenze','name_en'=>'Florence','name_de'=>null),
			array('id'=>255,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Forli','name_en'=>null,'name_de'=>null),
			array('id'=>256,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Frosinone','name_en'=>null,'name_de'=>null),
			array('id'=>257,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Genova','name_en'=>null,'name_de'=>null),
			array('id'=>258,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Gorizia','name_en'=>null,'name_de'=>null),
			array('id'=>259,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Grosseto','name_en'=>null,'name_de'=>null),
			array('id'=>260,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Imperia','name_en'=>null,'name_de'=>null),
			array('id'=>261,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Isernia','name_en'=>null,'name_de'=>null),
			array('id'=>262,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Crotone','name_en'=>null,'name_de'=>null),
			array('id'=>263,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Lecco','name_en'=>null,'name_de'=>null),
			array('id'=>264,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Lecce','name_en'=>null,'name_de'=>null),
			array('id'=>265,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Livorno','name_en'=>null,'name_de'=>null),
			array('id'=>266,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Lodi','name_en'=>null,'name_de'=>null),
			array('id'=>267,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Latina','name_en'=>null,'name_de'=>null),
			array('id'=>268,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Lucca','name_en'=>null,'name_de'=>null),
			array('id'=>269,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Macerata','name_en'=>null,'name_de'=>null),
			array('id'=>270,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Messina','name_en'=>null,'name_de'=>null),
			array('id'=>271,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Milano','name_en'=>null,'name_de'=>null),
			array('id'=>272,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Mantova','name_en'=>null,'name_de'=>null),
			array('id'=>273,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Modena','name_en'=>null,'name_de'=>null),
			array('id'=>274,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Massa Carrara','name_en'=>null,'name_de'=>null),
			array('id'=>275,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Matera','name_en'=>null,'name_de'=>null),
			array('id'=>276,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Napoli','name_en'=>'Naples','name_de'=>null),
			array('id'=>277,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Novara','name_en'=>null,'name_de'=>null),
			array('id'=>278,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Nuoro','name_en'=>null,'name_de'=>null),
			array('id'=>279,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Oristano','name_en'=>null,'name_de'=>null),
			array('id'=>280,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Palermo','name_en'=>null,'name_de'=>null),
			array('id'=>281,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Piacenza','name_en'=>null,'name_de'=>null),
			array('id'=>282,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Padova','name_en'=>null,'name_de'=>null),
			array('id'=>283,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Pescara','name_en'=>null,'name_de'=>null),
			array('id'=>284,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Perugia','name_en'=>null,'name_de'=>null),
			array('id'=>285,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Pisa','name_en'=>null,'name_de'=>null),
			array('id'=>286,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Pordenone','name_en'=>null,'name_de'=>null),
			array('id'=>287,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Parma','name_en'=>null,'name_de'=>null),
			array('id'=>288,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Pesora','name_en'=>null,'name_de'=>null),
			array('id'=>289,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Pistoia','name_en'=>null,'name_de'=>null),
			array('id'=>290,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Pavia','name_en'=>null,'name_de'=>null),
			array('id'=>291,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Prato','name_en'=>null,'name_de'=>null),
			array('id'=>292,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Potenza','name_en'=>null,'name_de'=>null),
			array('id'=>293,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Ravenna','name_en'=>null,'name_de'=>null),
			array('id'=>294,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Reggio Calabria','name_en'=>null,'name_de'=>null),
			array('id'=>295,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Reggio Emilia','name_en'=>null,'name_de'=>null),
			array('id'=>296,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Ragusa','name_en'=>null,'name_de'=>null),
			array('id'=>297,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Rieti','name_en'=>null,'name_de'=>null),
			array('id'=>298,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Roma','name_en'=>'Rome','name_de'=>null),
			array('id'=>299,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Rimini','name_en'=>null,'name_de'=>null),
			array('id'=>300,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Rovigo','name_en'=>null,'name_de'=>null),
			array('id'=>301,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Salerno','name_en'=>null,'name_de'=>null),
			array('id'=>302,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Siena','name_en'=>null,'name_de'=>null),
			array('id'=>303,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Sondrio','name_en'=>null,'name_de'=>null),
			array('id'=>304,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'La Spezia','name_en'=>null,'name_de'=>null),
			array('id'=>305,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Siracusa','name_en'=>null,'name_de'=>null),
			array('id'=>306,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Sassari','name_en'=>null,'name_de'=>null),
			array('id'=>307,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Savona','name_en'=>null,'name_de'=>null),
			array('id'=>308,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Taranto','name_en'=>null,'name_de'=>null),
			array('id'=>309,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Teramo','name_en'=>null,'name_de'=>null),
			array('id'=>310,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Trento','name_en'=>null,'name_de'=>null),
			array('id'=>311,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Torino','name_en'=>null,'name_de'=>null),
			array('id'=>312,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Trapani','name_en'=>null,'name_de'=>null),
			array('id'=>313,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Terni','name_en'=>null,'name_de'=>null),
			array('id'=>314,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Trieste','name_en'=>null,'name_de'=>null),
			array('id'=>315,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Treviso','name_en'=>null,'name_de'=>null),
			array('id'=>316,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Udine','name_en'=>null,'name_de'=>null),
			array('id'=>317,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Varese','name_en'=>null,'name_de'=>null),
			array('id'=>318,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Vercelli','name_en'=>null,'name_de'=>null),
			array('id'=>319,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Venezia','name_en'=>'Venice','name_de'=>'Venedig'),
			array('id'=>320,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Vicenza','name_en'=>null,'name_de'=>null),
			array('id'=>321,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Verbania','name_en'=>null,'name_de'=>null),
			array('id'=>322,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Verona','name_en'=>null,'name_de'=>null),
			array('id'=>323,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Viterbo','name_en'=>null,'name_de'=>null),
			array('id'=>324,'country_iso_3'=>'ITA','zone_code'=>NULL,'name_local'=>'Vibo Valentia','name_en'=>null,'name_de'=>null),
			array('id'=>325,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Alderney','name_en'=>null,'name_de'=>null),
			array('id'=>326,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Armagh','name_en'=>null,'name_de'=>null),
			array('id'=>327,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Antrim','name_en'=>null,'name_de'=>null),
			array('id'=>328,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Borders','name_en'=>null,'name_de'=>null),
			array('id'=>329,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Bedfordshire','name_en'=>null,'name_de'=>null),
			array('id'=>330,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Birmingham','name_en'=>null,'name_de'=>null),
			array('id'=>331,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Blaenau Gwent','name_en'=>null,'name_de'=>null),
			array('id'=>332,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Bridgend','name_en'=>null,'name_de'=>null),
			array('id'=>333,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Berkshire','name_en'=>null,'name_de'=>null),
			array('id'=>334,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Bristol','name_en'=>null,'name_de'=>null),
			array('id'=>335,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Buckinghamshire','name_en'=>null,'name_de'=>null),
			array('id'=>336,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Caerphilly','name_en'=>null,'name_de'=>null),
			array('id'=>337,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Cardiff','name_en'=>null,'name_de'=>null),
			array('id'=>338,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Carmarthenshire','name_en'=>null,'name_de'=>null),
			array('id'=>339,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Cumbria','name_en'=>null,'name_de'=>null),
			array('id'=>340,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Cambridgeshire','name_en'=>null,'name_de'=>null),
			array('id'=>341,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Ceredigion','name_en'=>null,'name_de'=>null),
			array('id'=>342,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Channel Islands','name_en'=>null,'name_de'=>null),
			array('id'=>343,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Cheshire','name_en'=>null,'name_de'=>null),
			array('id'=>344,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Clwyd','name_en'=>null,'name_de'=>null),
			array('id'=>345,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Cornwall','name_en'=>null,'name_de'=>null),
			array('id'=>346,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Conway','name_en'=>null,'name_de'=>null),
			array('id'=>347,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Central','name_en'=>null,'name_de'=>null),
			array('id'=>348,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Cleveland','name_en'=>null,'name_de'=>null),
			array('id'=>349,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Denbighshire','name_en'=>null,'name_de'=>null),
			array('id'=>350,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Dyfed','name_en'=>null,'name_de'=>null),
			array('id'=>351,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Dumfries and Galloway','name_en'=>null,'name_de'=>null),
			array('id'=>352,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Durham','name_en'=>null,'name_de'=>null),
			array('id'=>353,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Dorset','name_en'=>null,'name_de'=>null),
			array('id'=>354,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Devon','name_en'=>null,'name_de'=>null),
			array('id'=>355,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Down','name_en'=>null,'name_de'=>null),
			array('id'=>356,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Derbyshire','name_en'=>null,'name_de'=>null),
			array('id'=>357,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Essex','name_en'=>null,'name_de'=>null),
			array('id'=>358,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Fermanagh','name_en'=>null,'name_de'=>null),
			array('id'=>359,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Fife','name_en'=>null,'name_de'=>null),
			array('id'=>360,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Flintshire','name_en'=>null,'name_de'=>null),
			array('id'=>361,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'County Fermanagh','name_en'=>null,'name_de'=>null),
			array('id'=>362,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Gwynedd','name_en'=>null,'name_de'=>null),
			array('id'=>363,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Gloucestershire','name_en'=>null,'name_de'=>null),
			array('id'=>364,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Gloucester','name_en'=>null,'name_de'=>null),
			array('id'=>365,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Mid Glamorgan','name_en'=>null,'name_de'=>null),
			array('id'=>366,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'South Glamorgan','name_en'=>null,'name_de'=>null),
			array('id'=>367,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'West Glamorgan','name_en'=>null,'name_de'=>null),
			array('id'=>368,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Grampian','name_en'=>null,'name_de'=>null),
			array('id'=>369,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Guernsey','name_en'=>null,'name_de'=>null),
			array('id'=>370,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Gwent','name_en'=>null,'name_de'=>null),
			array('id'=>371,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Humberside','name_en'=>null,'name_de'=>null),
			array('id'=>372,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Hertfordshire','name_en'=>null,'name_de'=>null),
			array('id'=>373,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Highlands','name_en'=>null,'name_de'=>null),
			array('id'=>374,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Hampshire','name_en'=>null,'name_de'=>null),
			array('id'=>375,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Hereford and Worcester','name_en'=>null,'name_de'=>null),
			array('id'=>376,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Isle of Man','name_en'=>null,'name_de'=>null),
			array('id'=>377,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Isle of Wight','name_en'=>null,'name_de'=>null),
			array('id'=>378,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Isle of Anglesey','name_en'=>null,'name_de'=>null),
			array('id'=>379,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Jersey','name_en'=>null,'name_de'=>null),
			array('id'=>380,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Kent','name_en'=>null,'name_de'=>null),
			array('id'=>381,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Lincolnshire','name_en'=>null,'name_de'=>null),
			array('id'=>382,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Greater London','name_en'=>null,'name_de'=>null),
			array('id'=>383,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Londonderry','name_en'=>null,'name_de'=>null),
			array('id'=>384,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Leicestershire','name_en'=>null,'name_de'=>null),
			array('id'=>385,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Lancashire','name_en'=>null,'name_de'=>null),
			array('id'=>386,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'London','name_en'=>null,'name_de'=>null),
			array('id'=>387,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'East Lothian','name_en'=>null,'name_de'=>null),
			array('id'=>388,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Mid Lothian','name_en'=>null,'name_de'=>null),
			array('id'=>389,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'West Lothian','name_en'=>null,'name_de'=>null),
			array('id'=>390,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Greater Manchester','name_en'=>null,'name_de'=>null),
			array('id'=>391,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Merthyr Tydfil','name_en'=>null,'name_de'=>null),
			array('id'=>392,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Monmouthshire','name_en'=>null,'name_de'=>null),
			array('id'=>393,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Merseyside','name_en'=>null,'name_de'=>null),
			array('id'=>394,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Neath Port Talbot','name_en'=>null,'name_de'=>null),
			array('id'=>395,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Newport','name_en'=>null,'name_de'=>null),
			array('id'=>396,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Northamptonshire','name_en'=>null,'name_de'=>null),
			array('id'=>397,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Northumberland','name_en'=>null,'name_de'=>null),
			array('id'=>398,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Norfolk','name_en'=>null,'name_de'=>null),
			array('id'=>399,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Nottinghamshire','name_en'=>null,'name_de'=>null),
			array('id'=>400,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'North West Highlands','name_en'=>null,'name_de'=>null),
			array('id'=>401,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Oxfordshire','name_en'=>null,'name_de'=>null),
			array('id'=>402,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Orkney','name_en'=>null,'name_de'=>null),
			array('id'=>403,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Pembrokeshire','name_en'=>null,'name_de'=>null),
			array('id'=>404,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Powys','name_en'=>null,'name_de'=>null),
			array('id'=>405,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Strathclyde','name_en'=>null,'name_de'=>null),
			array('id'=>406,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Staffordshire','name_en'=>null,'name_de'=>null),
			array('id'=>407,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Suffolk','name_en'=>null,'name_de'=>null),
			array('id'=>408,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Shetland','name_en'=>null,'name_de'=>null),
			array('id'=>409,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Somerset','name_en'=>null,'name_de'=>null),
			array('id'=>410,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Shropshire','name_en'=>null,'name_de'=>null),
			array('id'=>411,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Sark','name_en'=>null,'name_de'=>null),
			array('id'=>412,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Surrey','name_en'=>null,'name_de'=>null),
			array('id'=>413,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Swansea','name_en'=>null,'name_de'=>null),
			array('id'=>414,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'East Sussex','name_en'=>null,'name_de'=>null),
			array('id'=>415,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'West Sussex','name_en'=>null,'name_de'=>null),
			array('id'=>416,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Rhondda Cynon Taff','name_en'=>null,'name_de'=>null),
			array('id'=>417,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Torfaen','name_en'=>null,'name_de'=>null),
			array('id'=>418,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Tyne and Wear','name_en'=>null,'name_de'=>null),
			array('id'=>419,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Tyrone','name_en'=>null,'name_de'=>null),
			array('id'=>420,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Tayside','name_en'=>null,'name_de'=>null),
			array('id'=>421,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Vale of Glamorgan','name_en'=>null,'name_de'=>null),
			array('id'=>422,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Western Isles','name_en'=>null,'name_de'=>null),
			array('id'=>423,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Warwickshire','name_en'=>null,'name_de'=>null),
			array('id'=>424,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Wiltshire','name_en'=>null,'name_de'=>null),
			array('id'=>425,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'West Midlands','name_en'=>null,'name_de'=>null),
			array('id'=>426,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'Wrexham','name_en'=>null,'name_de'=>null),
			array('id'=>427,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'North Yorkshire','name_en'=>null,'name_de'=>null),
			array('id'=>428,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'South Yorkshire','name_en'=>null,'name_de'=>null),
			array('id'=>429,'country_iso_3'=>'GBR','zone_code'=>NULL,'name_local'=>'West Yorkshire','name_en'=>null,'name_de'=>null),
			array('id'=>430,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Carlow','name_en'=>null,'name_de'=>null),
			array('id'=>431,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Cavan','name_en'=>null,'name_de'=>null),
			array('id'=>432,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Clare','name_en'=>null,'name_de'=>null),
			array('id'=>433,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Cork','name_en'=>null,'name_de'=>null),
			array('id'=>434,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Donegal','name_en'=>null,'name_de'=>null),
			array('id'=>435,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Dublin','name_en'=>null,'name_de'=>null),
			array('id'=>436,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Galway','name_en'=>null,'name_de'=>null),
			array('id'=>437,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Kerry','name_en'=>null,'name_de'=>null),
			array('id'=>438,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Kildare','name_en'=>null,'name_de'=>null),
			array('id'=>439,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Kilkenny','name_en'=>null,'name_de'=>null),
			array('id'=>440,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Laois','name_en'=>null,'name_de'=>null),
			array('id'=>441,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Leitrim','name_en'=>null,'name_de'=>null),
			array('id'=>442,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Limerick','name_en'=>null,'name_de'=>null),
			array('id'=>443,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Longford','name_en'=>null,'name_de'=>null),
			array('id'=>444,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Louth','name_en'=>null,'name_de'=>null),
			array('id'=>445,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Mayo','name_en'=>null,'name_de'=>null),
			array('id'=>446,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Meath','name_en'=>null,'name_de'=>null),
			array('id'=>447,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Monaghan','name_en'=>null,'name_de'=>null),
			array('id'=>448,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Offaly','name_en'=>null,'name_de'=>null),
			array('id'=>449,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Roscommon','name_en'=>null,'name_de'=>null),
			array('id'=>450,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Sligo','name_en'=>null,'name_de'=>null),
			array('id'=>451,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Tipperary','name_en'=>null,'name_de'=>null),
			array('id'=>452,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Waterford','name_en'=>null,'name_de'=>null),
			array('id'=>453,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Westmeath','name_en'=>null,'name_de'=>null),
			array('id'=>454,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Wexford','name_en'=>null,'name_de'=>null),
			array('id'=>455,'country_iso_3'=>'IRL','zone_code'=>NULL,'name_local'=>'Wicklow','name_en'=>null,'name_de'=>null),
			array('id'=>456,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Acre','name_en'=>null,'name_de'=>null),
			array('id'=>457,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Amapá','name_en'=>null,'name_de'=>null),
			array('id'=>458,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Alagoas','name_en'=>null,'name_de'=>null),
			array('id'=>459,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Amazonas','name_en'=>null,'name_de'=>null),
			array('id'=>460,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Bahia','name_en'=>null,'name_de'=>null),
			array('id'=>461,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Ceará','name_en'=>null,'name_de'=>null),
			array('id'=>462,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Distrito Federal','name_en'=>null,'name_de'=>null),
			array('id'=>463,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Espírito Santo','name_en'=>null,'name_de'=>null),
			array('id'=>464,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Goiás','name_en'=>null,'name_de'=>null),
			array('id'=>465,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Maranhão','name_en'=>null,'name_de'=>null),
			array('id'=>466,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Minas Gerais','name_en'=>null,'name_de'=>null),
			array('id'=>467,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Mato Grosso do Sul','name_en'=>null,'name_de'=>null),
			array('id'=>468,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Mato Grosso','name_en'=>null,'name_de'=>null),
			array('id'=>469,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Pará','name_en'=>null,'name_de'=>null),
			array('id'=>470,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Paraíba','name_en'=>null,'name_de'=>null),
			array('id'=>471,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Pernambuco','name_en'=>null,'name_de'=>null),
			array('id'=>472,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Piauí','name_en'=>null,'name_de'=>null),
			array('id'=>473,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Paraná','name_en'=>null,'name_de'=>null),
			array('id'=>474,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Rio de Janeiro','name_en'=>null,'name_de'=>null),
			array('id'=>475,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Rio Grande do Norte','name_en'=>null,'name_de'=>null),
			array('id'=>476,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Rondônia','name_en'=>null,'name_de'=>null),
			array('id'=>477,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Roraima','name_en'=>null,'name_de'=>null),
			array('id'=>478,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Rio Grande do Sul','name_en'=>null,'name_de'=>null),
			array('id'=>479,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Santa Catarina','name_en'=>null,'name_de'=>null),
			array('id'=>480,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Sergipe','name_en'=>null,'name_de'=>null),
			array('id'=>481,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'São Paulo','name_en'=>null,'name_de'=>null),
			array('id'=>482,'country_iso_3'=>'BRA','zone_code'=>NULL,'name_local'=>'Tocantins','name_en'=>null,'name_de'=>null),
			array('id'=>483,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Drenthe','name_en'=>null,'name_de'=>null),
			array('id'=>484,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Flevoland','name_en'=>null,'name_de'=>null),
			array('id'=>485,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Friesland','name_en'=>null,'name_de'=>null),
			array('id'=>486,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Gelderland','name_en'=>null,'name_de'=>null),
			array('id'=>487,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Groningen','name_en'=>null,'name_de'=>null),
			array('id'=>488,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Limburg','name_en'=>null,'name_de'=>null),
			array('id'=>489,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Noord-Brabant','name_en'=>null,'name_de'=>null),
			array('id'=>490,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Noord-Holland','name_en'=>null,'name_de'=>null),
			array('id'=>491,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Overijssel','name_en'=>null,'name_de'=>null),
			array('id'=>492,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Utrecht','name_en'=>null,'name_de'=>null),
			array('id'=>493,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Zuid-Holland','name_en'=>null,'name_de'=>null),
			array('id'=>494,'country_iso_3'=>'NLD','zone_code'=>NULL,'name_local'=>'Zeeland','name_en'=>null,'name_de'=>null)
		);

		$this->setArray($array);

	}

	/**
	 * Takes $this->_data and converts it into a Doctrine_Collection
	 *
	 * @return void
	 */
	protected function _generateDataCollection()
	{
		$this->_dataCollection = new Doctrine_Collection($this->getModelClassName());

		foreach($this->_data as $data) {

			$countryZone = L8M_Doctrine_Record::factory($this->getModelClassName());
			$countryZone->merge($data);

			if ($data['name_en']) {
				$countryZone->Translation['en']->name = $data['name_en'];
			}
			if ($data['name_de']) {
				$countryZone->Translation['de']->name = $data['name_de'];
			}

			$this->_dataCollection->add($countryZone, $data['id']);
		}

	}

}