<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/admin/views/scripts/shop-product-status/edit.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: edit.phtml 7 2014-03-11 16:18:40Z nm $
 */

if (isset($this->modelModelColumn) &&
	isset($this->modelModelName)) {

	$modelName = $this->modelModelColumn . ' <strong>' . $this->modelModelName . '</strong> (ID: ' . $this->modelModelId . ')';
} else {
	$modelName = 'ID: ' . $this->modelModelId;
}

?>
<p><?php echo $this->translate('You are editing')?>: <?php echo $modelName; ?></p>
<?php

if (isset($this->modelForm)) {
	echo $this->modelForm;
}

$this->headLink()->appendStylesheet('/js/jquery/plugins/colorpicker/css/colorpicker.css', 'all');
$this->headScript()->appendFile('/js/jquery/plugins/colorpicker/js/colorpicker.js', 'text/javascript');
$this->headScript()->captureStart();

?>
$(document).ready(function() {
	$('#product_status_color_code').ColorPicker({
		onShow: function (colpkr) {
			$(colpkr).fadeIn(500);
			return false;
		},
		onHide: function (colpkr) {
			$(colpkr).fadeOut(500);
			return false;
		},
		onSubmit: function(hsb, hex, rgb, el) {
			$(el).val(hex);
			$(el).ColorPickerHide();
		},
		onBeforeShow: function () {
			$(this).ColorPickerSetColor(this.value);
		}
	});
});
<?php

$this->headScript()->captureEnd();
