<?php

/**
 * Default_Model_Base_Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_order_id
 * @property integer $house_type_id
 * @property integer $etage_id
 * @property boolean $lift
 * @property boolean $barrier_free
 * @property integer $room_number
 * @property string $working_hours_from
 * @property string $working_hours_till
 * @property string $pause_hours_from
 * @property string $pause_hours_till
 * @property integer $return_of_empties
 * @property Default_Model_Etage $Etage
 * @property Default_Model_HouseTypes $HouseType
 * @property Default_Model_ProductOrder $ProductOrder
 * @property Doctrine_Collection $DeliveryTime
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_Address extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('address');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('product_order_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('house_type_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('etage_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('lift', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('barrier_free', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('room_number', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('working_hours_from', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('working_hours_till', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('pause_hours_from', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('pause_hours_till', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('return_of_empties', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));


        $this->index('etage_id', array(
             'fields' => 
             array(
              0 => 'etage_id',
             ),
             ));
        $this->index('house_type_id', array(
             'fields' => 
             array(
              0 => 'house_type_id',
             ),
             ));
        $this->index('product_order_id', array(
             'fields' => 
             array(
              0 => 'product_order_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Etage as Etage', array(
             'local' => 'etage_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_HouseTypes as HouseType', array(
             'local' => 'house_type_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_ProductOrder as ProductOrder', array(
             'local' => 'product_order_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_DeliveryTime as DeliveryTime', array(
             'local' => 'id',
             'foreign' => 'address_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}