<?php

/**
 * Default_Model_Base_AssemblyM2nRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $assembly_id
 * @property integer $region_id
 * @property Default_Model_Assembly $Assembly
 * @property Default_Model_Region $Region
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_AssemblyM2nRegion extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('assembly_m2n_region');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('assembly_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));


        $this->index('assembly_id_idx', array(
             'fields' => 
             array(
              0 => 'assembly_id',
             ),
             ));
        $this->index('region_id_idx', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Assembly as Assembly', array(
             'local' => 'assembly_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Region as Region', array(
             'local' => 'region_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}