<?php

/**
 * Default_Model_Base_BackendAdminBoxesActionM2nBackendAdminBoxes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $backend_admin_boxes_id
 * @property integer $backend_admin_boxes_action_id
 * @property integer $position
 * @property Default_Model_BackendAdminBoxesAction $BackendAdminBoxesAction
 * @property Default_Model_BackendAdminBoxes $BackendAdminBoxes
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_BackendAdminBoxesActionM2nBackendAdminBoxes extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('backend_admin_boxes_action_m2n_backend_admin_boxes');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('backend_admin_boxes_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('backend_admin_boxes_action_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('position', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));


        $this->index('backend_admin_boxes_action_id', array(
             'fields' => 
             array(
              0 => 'backend_admin_boxes_action_id',
             ),
             ));
        $this->index('backend_admin_boxes_id', array(
             'fields' => 
             array(
              0 => 'backend_admin_boxes_id',
             ),
             ));
        $this->index('position_idx', array(
             'fields' => 
             array(
              0 => 'position',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_BackendAdminBoxesAction as BackendAdminBoxesAction', array(
             'local' => 'backend_admin_boxes_action_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_BackendAdminBoxes as BackendAdminBoxes', array(
             'local' => 'backend_admin_boxes_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}