<?php

/**
 * Default_Model_Base_BackendAdminBoxesAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property integer $model_name_id
 * @property integer $action_id
 * @property boolean $count_not_new
 * @property string $name
 * @property string $title
 * @property Default_Model_Action $Action
 * @property Default_Model_ModelName $ModelName
 * @property Doctrine_Collection $BackendAdminBoxesActionM2nBackendAdminBoxes
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_BackendAdminBoxesAction extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('backend_admin_boxes_action');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('model_name_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('action_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('count_not_new', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));


        $this->index('model_name_id', array(
             'fields' => 
             array(
              0 => 'model_name_id',
             ),
             ));
        $this->index('action_id_idx', array(
             'fields' => 
             array(
              0 => 'action_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Action as Action', array(
             'local' => 'action_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_ModelName as ModelName', array(
             'local' => 'model_name_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_BackendAdminBoxesActionM2nBackendAdminBoxes as BackendAdminBoxesActionM2nBackendAdminBoxes', array(
             'local' => 'id',
             'foreign' => 'backend_admin_boxes_action_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'backend_admin_boxes_action_translation',
             'fields' => 
             array(
              0 => 'name',
              1 => 'title',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}