<?php

/**
 * Default_Model_Base_Brand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property string $name
 * @property integer $media_image_id
 * @property string $title
 * @property Default_Model_MediaImage $MediaImage
 * @property Doctrine_Collection $EntityM2nBrand
 * @property Doctrine_Collection $DatesM2nBrand
 * @property Doctrine_Collection $ProtocolM2nBrand
 * @property Doctrine_Collection $RegionDatesM2nBrand
 * @property Doctrine_Collection $SurveyM2nBrand
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_Brand extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('brand');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('media_image_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => 8,
             ));
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));

        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_MediaImage as MediaImage', array(
             'local' => 'media_image_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_EntityM2nBrand as EntityM2nBrand', array(
             'local' => 'id',
             'foreign' => 'brand_id'));

        $this->hasMany('Default_Model_DatesM2nBrand as DatesM2nBrand', array(
             'local' => 'id',
             'foreign' => 'brand_id'));

        $this->hasMany('Default_Model_ProtocolM2nBrand as ProtocolM2nBrand', array(
             'local' => 'id',
             'foreign' => 'brand_id'));

        $this->hasMany('Default_Model_RegionDatesM2nBrand as RegionDatesM2nBrand', array(
             'local' => 'id',
             'foreign' => 'brand_id'));

        $this->hasMany('Default_Model_SurveyM2nBrand as SurveyM2nBrand', array(
             'local' => 'id',
             'foreign' => 'brand_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'brand_translation',
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}