<?php

/**
 * Default_Model_Base_Controller
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $resource
 * @property integer $module_id
 * @property string $description
 * @property Default_Model_Module $Module
 * @property Doctrine_Collection $Action
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_Controller extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('controller');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '64',
             ));
        $this->hasColumn('resource', 'string', 128, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('module_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('module_id_idx', array(
             'fields' => 
             array(
              0 => 'module_id',
             ),
             ));
        $this->index('name_idx', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Module as Module', array(
             'local' => 'module_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_Action as Action', array(
             'local' => 'id',
             'foreign' => 'controller_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}