<?php

/**
 * Default_Model_Base_ContractType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property string $name
 * @property string $title
 * @property Doctrine_Collection $Entity
 * @property Doctrine_Collection $DatesM2nContractType
 * @property Doctrine_Collection $ProtocolM2nContractType
 * @property Doctrine_Collection $RegionDatesM2nContractType
 * @property Doctrine_Collection $SurveyM2nContractType
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ContractType extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('contract_type');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));

        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_Entity as Entity', array(
             'local' => 'id',
             'foreign' => 'contract_type_id'));

        $this->hasMany('Default_Model_DatesM2nContractType as DatesM2nContractType', array(
             'local' => 'id',
             'foreign' => 'contract_type_id'));

        $this->hasMany('Default_Model_ProtocolM2nContractType as ProtocolM2nContractType', array(
             'local' => 'id',
             'foreign' => 'contract_type_id'));

        $this->hasMany('Default_Model_RegionDatesM2nContractType as RegionDatesM2nContractType', array(
             'local' => 'id',
             'foreign' => 'contract_type_id'));

        $this->hasMany('Default_Model_SurveyM2nContractType as SurveyM2nContractType', array(
             'local' => 'id',
             'foreign' => 'contract_type_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'contract_type_translation',
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}