<?php

/**
 * Default_Model_Base_Country
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $iso_2
 * @property string $iso_3
 * @property integer $territory_iso_nr
 * @property string $name_local
 * @property string $name
 * @property Default_Model_Territory $TerritoryIsoNr
 * @property Doctrine_Collection $Entity
 * @property Doctrine_Collection $ProductOrder
 * @property Doctrine_Collection $CountryZone
 * @property Doctrine_Collection $Language
 * @property Doctrine_Collection $ShippingCountry
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_Country extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('iso_2', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('iso_3', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '3',
             ));
        $this->hasColumn('territory_iso_nr', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('name_local', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('territory_iso_nr_idx', array(
             'fields' => 
             array(
              0 => 'territory_iso_nr',
             ),
             ));
        $this->index('iso_2', array(
             'fields' => 
             array(
              0 => 'iso_2',
             ),
             ));
        $this->index('iso_3', array(
             'fields' => 
             array(
              0 => 'iso_3',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Territory as TerritoryIsoNr', array(
             'local' => 'territory_iso_nr',
             'foreign' => 'iso_nr'));

        $this->hasMany('Default_Model_Entity as Entity', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $this->hasMany('Default_Model_ProductOrder as ProductOrder', array(
             'local' => 'id',
             'foreign' => 'billing_country_id'));

        $this->hasMany('Default_Model_CountryZone as CountryZone', array(
             'local' => 'iso_3',
             'foreign' => 'country_iso_3'));

        $this->hasMany('Default_Model_Language as Language', array(
             'local' => 'iso_2',
             'foreign' => 'country_iso_2'));

        $this->hasMany('Default_Model_ShippingCountry as ShippingCountry', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'country_translation',
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}