<?php

/**
 * Default_Model_Base_CountryZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $country_iso_3
 * @property string $zone_code
 * @property string $name_local
 * @property string $name
 * @property Default_Model_Country $CountryIso3
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_CountryZone extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('country_zone');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('country_iso_3', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '3',
             ));
        $this->hasColumn('zone_code', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('name_local', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));


        $this->index('country_iso_3_idx', array(
             'fields' => 
             array(
              0 => 'country_iso_3',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Country as CountryIso3', array(
             'local' => 'country_iso_3',
             'foreign' => 'iso_3'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'country_zone_translation',
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}