<?php

/**
 * Default_Model_Base_CouponHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $coupon_id
 * @property decimal $value
 * @property integer $product_order_id
 * @property Default_Model_ProductOrder $ProductOrder
 * @property Default_Model_Coupon $Coupon
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_CouponHistory extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('coupon_history');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('coupon_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('value', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => '2',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('product_order_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));


        $this->index('product_order_id', array(
             'fields' => 
             array(
              0 => 'product_order_id',
             ),
             ));
        $this->index('coupon_id', array(
             'fields' => 
             array(
              0 => 'coupon_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_ProductOrder as ProductOrder', array(
             'local' => 'product_order_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Coupon as Coupon', array(
             'local' => 'coupon_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}