<?php

/**
 * Default_Model_Base_CrossSell
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product1_id
 * @property integer $product2_id
 * @property integer $counter
 * @property Default_Model_Product $Product1
 * @property Default_Model_Product $Product2
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_CrossSell extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('cross_sell');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('product1_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('product2_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('counter', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));


        $this->index('product1_id', array(
             'fields' => 
             array(
              0 => 'product1_id',
             ),
             ));
        $this->index('product2_id', array(
             'fields' => 
             array(
              0 => 'product2_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Product as Product1', array(
             'local' => 'product1_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Product as Product2', array(
             'local' => 'product2_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}