<?php

/**
 * Default_Model_Base_EntityModelListConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property integer $model_list_id
 * @property integer $entity_id
 * @property integer $rp
 * @property clob $sortname
 * @property string $sortorder
 * @property string $qtype
 * @property clob $query
 * @property Default_Model_ModelList $ModelList
 * @property Default_Model_Entity $Entity
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_EntityModelListConfig extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_model_list_config');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('model_list_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('entity_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('rp', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('sortname', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('sortorder', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));
        $this->hasColumn('qtype', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('query', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));


        $this->index('model_list_id_idx', array(
             'fields' => 
             array(
              0 => 'model_list_id',
             ),
             ));
        $this->index('entity_id_idx', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_ModelList as ModelList', array(
             'local' => 'model_list_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Entity as Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}