<?php

/**
 * Default_Model_Base_EntityM2nBrandOptionModel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property integer $brand_option_model_id
 * @property integer $position
 * @property Default_Model_Entity $Entity
 * @property Default_Model_BrandOptionModel $BrandOptionModel
 * @property Doctrine_Collection $EntityM2nBrandOptionModelValues
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_EntityM2nBrandOptionModel extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_m2n_brand_option_model');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('entity_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('brand_option_model_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('position', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));


        $this->index('position_idx', array(
             'fields' => 
             array(
              0 => 'position',
             ),
             ));
        $this->index('entity_id_idx', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->index('brand_option_model_id_idx', array(
             'fields' => 
             array(
              0 => 'brand_option_model_id',
              1 => 'entity_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Entity as Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_BrandOptionModel as BrandOptionModel', array(
             'local' => 'brand_option_model_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_EntityM2nBrandOptionModelValues as EntityM2nBrandOptionModelValues', array(
             'local' => 'id',
             'foreign' => 'entity_m2n_brand_option_model_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}