<?php

/**
 * Default_Model_Base_EntityUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $ProductOrder
 * @property Doctrine_Collection $Coupon
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_EntityUser extends Default_Model_Entity
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_ProductOrder as ProductOrder', array(
             'local' => 'id',
             'foreign' => 'entity_user_id'));

        $this->hasMany('Default_Model_Coupon as Coupon', array(
             'local' => 'id',
             'foreign' => 'entity_user_id'));
    }
}