<?php

/**
 * Default_Model_Base_EntityLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_id
 * @property integer $entity_log_message_id
 * @property decimal $latitude
 * @property decimal $longitude
 * @property decimal $accuracy
 * @property decimal $altitude
 * @property decimal $altitude_accuracy
 * @property decimal $heading
 * @property decimal $speed
 * @property string $remote_ip
 * @property Default_Model_EntityLogMessage $EntityLogMessage
 * @property Default_Model_Entity $Entity
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_EntityLog extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_log');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('entity_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('entity_log_message_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('latitude', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => '10',
             'length' => '15',
             ));
        $this->hasColumn('longitude', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => '10',
             'length' => '15',
             ));
        $this->hasColumn('accuracy', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => '5',
             'length' => '10',
             ));
        $this->hasColumn('altitude', 'decimal', 14, array(
             'type' => 'decimal',
             'scale' => '7',
             'length' => '14',
             ));
        $this->hasColumn('altitude_accuracy', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => '6',
             'length' => '12',
             ));
        $this->hasColumn('heading', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => '3',
             'length' => '10',
             ));
        $this->hasColumn('speed', 'decimal', 12, array(
             'type' => 'decimal',
             'scale' => '4',
             'length' => '12',
             ));
        $this->hasColumn('remote_ip', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));


        $this->index('entity_log_message_id_idx', array(
             'fields' => 
             array(
              0 => 'entity_log_message_id',
             ),
             ));
        $this->index('entity_id_idx', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_EntityLogMessage as EntityLogMessage', array(
             'local' => 'entity_log_message_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Entity as Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}