<?php

/**
 * Default_Model_Base_EntityM2nBrandOptionModelValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entity_m2n_brand_option_model_id
 * @property boolean $is_member
 * @property integer $sell
 * @property integer $sport
 * @property integer $volume
 * @property integer $status
 * @property Default_Model_EntityM2nBrandOptionModel $EntityM2nBrandOptionModel
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_EntityM2nBrandOptionModelValues extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('entity_m2n_brand_option_model_values');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('entity_m2n_brand_option_model_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('is_member', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('sell', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('sport', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('volume', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('status', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));


        $this->index('entity_m2n_brand_option_model_id_idx', array(
             'fields' => 
             array(
              0 => 'entity_m2n_brand_option_model_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_EntityM2nBrandOptionModel as EntityM2nBrandOptionModel', array(
             'local' => 'entity_m2n_brand_option_model_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}