<?php

/**
 * Default_Model_Base_InfoPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property string $name
 * @property integer $info_page_id
 * @property integer $position
 * @property string $keywords
 * @property clob $description
 * @property string $menu_name
 * @property string $title
 * @property string $headline
 * @property string $subheadline
 * @property clob $content
 * @property Default_Model_InfoPage $InfoPage
 * @property Doctrine_Collection $MediaImageM2nInfoPage
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_InfoPage extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('info_page');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('info_page_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('position', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('menu_name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('headline', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('subheadline', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('content', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));


        $this->index('position_idx', array(
             'fields' => 
             array(
              0 => 'position',
             ),
             ));
        $this->index('info_page_id_idx', array(
             'fields' => 
             array(
              0 => 'info_page_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_InfoPage as InfoPage', array(
             'local' => 'info_page_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_MediaImageM2nInfoPage as MediaImageM2nInfoPage', array(
             'local' => 'id',
             'foreign' => 'info_page_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'info_page_translation',
             'fields' => 
             array(
              0 => 'keywords',
              1 => 'description',
              2 => 'menu_name',
              3 => 'title',
              4 => 'headline',
              5 => 'subheadline',
              6 => 'content',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}