<?php

/**
 * Default_Model_Base_Language
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $iso_2
 * @property string $country_iso_2
 * @property clob $collalte_locale
 * @property clob $name_local
 * @property boolean $is_sacred
 * @property boolean $is_constructed
 * @property clob $name
 * @property Default_Model_Country $CountryIso2
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_Language extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('language');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('iso_2', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('country_iso_2', 'string', 2, array(
             'type' => 'string',
             'length' => '2',
             ));
        $this->hasColumn('collalte_locale', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('name_local', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => '65535',
             ));
        $this->hasColumn('is_sacred', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_constructed', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('name', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));


        $this->index('country_iso_2_idx', array(
             'fields' => 
             array(
              0 => 'country_iso_2',
             ),
             ));
        $this->index('iso_2', array(
             'fields' => 
             array(
              0 => 'iso_2',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Country as CountryIso2', array(
             'local' => 'country_iso_2',
             'foreign' => 'iso_2'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'language_translation',
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}