<?php

/**
 * Default_Model_Base_MediaImageEdit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $original_image_id
 * @property integer $edited_image_id
 * @property clob $edit_data
 * @property string $image_resource
 * @property Default_Model_Media $OriginalImage
 * @property Default_Model_Media $EditedImage
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_MediaImageEdit extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('media_image_edit');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('original_image_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('edited_image_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('edit_data', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('image_resource', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));


        $this->index('original_image_id_idx', array(
             'fields' => 
             array(
              0 => 'original_image_id',
             ),
             ));
        $this->index('edited_image_id_idx', array(
             'fields' => 
             array(
              0 => 'edited_image_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Media as OriginalImage', array(
             'local' => 'original_image_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Media as EditedImage', array(
             'local' => 'edited_image_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}