<?php

/**
 * Default_Model_Base_MediaImageInstance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Default_Model_MediaImage $MediaImage
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_MediaImageInstance extends Default_Model_MediaImage
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_MediaImage as MediaImage', array(
             'local' => 'media_image_id',
             'foreign' => 'id'));
    }
}