<?php

/**
 * Default_Model_Base_MediaShockwave
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_MediaShockwave extends Default_Model_Media
{
    public function setUp()
    {
        parent::setUp();
        
    }
}