<?php

/**
 * Default_Model_Base_MediaImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Entity
 * @property Doctrine_Collection $MediaImageInstance
 * @property Doctrine_Collection $Product
 * @property Doctrine_Collection $ProductGroup
 * @property Doctrine_Collection $ProductOrderItem
 * @property Doctrine_Collection $ProductM2nMediaImage
 * @property Doctrine_Collection $PaymentService
 * @property Doctrine_Collection $Producer
 * @property Doctrine_Collection $Flyer
 * @property Doctrine_Collection $FlyerImages
 * @property Doctrine_Collection $ProductOptionItems
 * @property Doctrine_Collection $Team
 * @property Doctrine_Collection $BackgroundImage
 * @property Doctrine_Collection $ImageConfig
 * @property Doctrine_Collection $MediaImageM2nInfoPage
 * @property Doctrine_Collection $MediaImageM2nAction
 * @property Doctrine_Collection $ContentBox
 * @property Doctrine_Collection $Commission
 * @property Doctrine_Collection $CommissionM2nMediaImage
 * @property Doctrine_Collection $Region
 * @property Doctrine_Collection $Brand
 * @property Doctrine_Collection $TeamMembers
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_MediaImage extends Default_Model_Media
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_Entity as Entity', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_MediaImageInstance as MediaImageInstance', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_Product as Product', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_ProductGroup as ProductGroup', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_ProductOrderItem as ProductOrderItem', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_ProductM2nMediaImage as ProductM2nMediaImage', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_PaymentService as PaymentService', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_Producer as Producer', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_Flyer as Flyer', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_FlyerImages as FlyerImages', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_ProductOptionItems as ProductOptionItems', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_Team as Team', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_BackgroundImage as BackgroundImage', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_ImageConfig as ImageConfig', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_MediaImageM2nInfoPage as MediaImageM2nInfoPage', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_MediaImageM2nAction as MediaImageM2nAction', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_ContentBox as ContentBox', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_Commission as Commission', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_CommissionM2nMediaImage as CommissionM2nMediaImage', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_Region as Region', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_Brand as Brand', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));

        $this->hasMany('Default_Model_TeamMembers as TeamMembers', array(
             'local' => 'id',
             'foreign' => 'media_image_id'));
    }
}