<?php

/**
 * Default_Model_Base_ModelListEditIgnore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $model_column_name_id
 * @property integer $model_list_id
 * @property Default_Model_ModelColumnName $ModelColumnName
 * @property Default_Model_ModelList $ModelList
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ModelListEditIgnore extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('model_list_edit_ignore');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('model_column_name_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('model_list_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));


        $this->index('model_column_name_id', array(
             'fields' => 
             array(
              0 => 'model_column_name_id',
             ),
             ));
        $this->index('model_list_id', array(
             'fields' => 
             array(
              0 => 'model_list_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_ModelColumnName as ModelColumnName', array(
             'local' => 'model_column_name_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_ModelList as ModelList', array(
             'local' => 'model_list_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}