<?php

/**
 * Default_Model_Base_ModelList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_short
 * @property string $default_sort
 * @property boolean $button_edit
 * @property boolean $button_add
 * @property boolean $button_delete
 * @property integer $width
 * @property integer $height
 * @property string $title
 * @property Doctrine_Collection $ModelListColumn
 * @property Doctrine_Collection $ModelListEditIgnore
 * @property Doctrine_Collection $ModelListWhere
 * @property Doctrine_Collection $EntityModelListConfig
 * @property Doctrine_Collection $ModelListExport
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ModelList extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('model_list');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('name_short', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('default_sort', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('button_edit', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('button_add', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('button_delete', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('width', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('height', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_ModelListColumn as ModelListColumn', array(
             'local' => 'id',
             'foreign' => 'model_list_id'));

        $this->hasMany('Default_Model_ModelListEditIgnore as ModelListEditIgnore', array(
             'local' => 'id',
             'foreign' => 'model_list_id'));

        $this->hasMany('Default_Model_ModelListWhere as ModelListWhere', array(
             'local' => 'id',
             'foreign' => 'model_list_id'));

        $this->hasMany('Default_Model_EntityModelListConfig as EntityModelListConfig', array(
             'local' => 'id',
             'foreign' => 'model_list_id'));

        $this->hasMany('Default_Model_ModelListExport as ModelListExport', array(
             'local' => 'id',
             'foreign' => 'model_list_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'model_list_translation',
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}