<?php

/**
 * Default_Model_Base_ModelName
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $ModelColumnName
 * @property Doctrine_Collection $ModelListConnection
 * @property Doctrine_Collection $ProductOptionModel
 * @property Doctrine_Collection $BackendAdminBoxesAction
 * @property Doctrine_Collection $ModelMarkedForEditor
 * @property Doctrine_Collection $BrandOptionModel
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ModelName extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('model_name');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));

        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_ModelColumnName as ModelColumnName', array(
             'local' => 'id',
             'foreign' => 'model_name_id'));

        $this->hasMany('Default_Model_ModelListConnection as ModelListConnection', array(
             'local' => 'id',
             'foreign' => 'model_name_id'));

        $this->hasMany('Default_Model_ProductOptionModel as ProductOptionModel', array(
             'local' => 'id',
             'foreign' => 'model_name_id'));

        $this->hasMany('Default_Model_BackendAdminBoxesAction as BackendAdminBoxesAction', array(
             'local' => 'id',
             'foreign' => 'model_name_id'));

        $this->hasMany('Default_Model_ModelMarkedForEditor as ModelMarkedForEditor', array(
             'local' => 'id',
             'foreign' => 'model_name_id'));

        $this->hasMany('Default_Model_BrandOptionModel as BrandOptionModel', array(
             'local' => 'id',
             'foreign' => 'model_name_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}