<?php

/**
 * Default_Model_Base_ModelListConnection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property string $join_on_short
 * @property string $name_alias
 * @property integer $model_name_id
 * @property string $replace_with_column
 * @property boolean $is_foreign
 * @property string $local_key
 * @property string $foreign_key
 * @property Default_Model_ModelName $ModelName
 * @property Doctrine_Collection $ModelListColumn
 * @property Doctrine_Collection $ModelListWhere
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ModelListConnection extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('model_list_connection');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('join_on_short', 'string', 45, array(
             'type' => 'string',
             'length' => '45',
             ));
        $this->hasColumn('name_alias', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('model_name_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('replace_with_column', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_foreign', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('local_key', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('foreign_key', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('model_name_id', array(
             'fields' => 
             array(
              0 => 'model_name_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_ModelName as ModelName', array(
             'local' => 'model_name_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_ModelListColumn as ModelListColumn', array(
             'local' => 'id',
             'foreign' => 'model_list_connection_id'));

        $this->hasMany('Default_Model_ModelListWhere as ModelListWhere', array(
             'local' => 'id',
             'foreign' => 'model_list_connection_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}