<?php

/**
 * Default_Model_Base_ProductM2nProductOptionModelValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_m2n_product_option_model_id
 * @property integer $referenced_id
 * @property boolean $disabled
 * @property decimal $price
 * @property Default_Model_ProductM2nProductOptionModel $ProductM2nProductOptionModel
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ProductM2nProductOptionModelValues extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('product_m2n_product_option_model_values');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('product_m2n_product_option_model_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('referenced_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('price', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '10',
             ));


        $this->index('product_m2n_product_option_model_id_idx', array(
             'fields' => 
             array(
              0 => 'product_m2n_product_option_model_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_ProductM2nProductOptionModel as ProductM2nProductOptionModel', array(
             'local' => 'product_m2n_product_option_model_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}