<?php

/**
 * Default_Model_Base_ProductOrderItemUnits
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_order_item_id
 * @property clob $form_short
 * @property clob $form_value
 * @property Default_Model_ProductOrderItem $ProductOrderItem
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ProductOrderItemUnits extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('product_order_item_units');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('product_order_item_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('form_short', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('form_value', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));


        $this->index('product_order_item_id', array(
             'fields' => 
             array(
              0 => 'product_order_item_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_ProductOrderItem as ProductOrderItem', array(
             'local' => 'product_order_item_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}