<?php

/**
 * Default_Model_Base_ProductOptions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property string $title
 * @property string $sub_title
 * @property Doctrine_Collection $ProductsOptions
 * @property Doctrine_Collection $ProductOptionsM2nProductOptionItems
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ProductOptions extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('product_options');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '150',
             ));
        $this->hasColumn('sub_title', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '150',
             ));

        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Default_Model_ProductsOptions as ProductsOptions', array(
             'local' => 'id',
             'foreign' => 'product_options_id'));

        $this->hasMany('Default_Model_ProductOptionsM2nProductOptionItems as ProductOptionsM2nProductOptionItems', array(
             'local' => 'id',
             'foreign' => 'product_options_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'product_options_translation',
             'fields' => 
             array(
              0 => 'title',
              1 => 'sub_title',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}