<?php

/**
 * Default_Model_Base_ProductM2nProductOptionModel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property integer $product_option_model_id
 * @property integer $position
 * @property Default_Model_Product $Product
 * @property Default_Model_ProductOptionModel $ProductOptionModel
 * @property Doctrine_Collection $ProductM2nProductOptionModelValues
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ProductM2nProductOptionModel extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('product_m2n_product_option_model');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('product_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('product_option_model_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('position', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));


        $this->index('product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->index('product_option_model_id', array(
             'fields' => 
             array(
              0 => 'product_option_model_id',
             ),
             ));
        $this->index('position_idx', array(
             'fields' => 
             array(
              0 => 'position',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Product as Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_ProductOptionModel as ProductOptionModel', array(
             'local' => 'product_option_model_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_ProductM2nProductOptionModelValues as ProductM2nProductOptionModelValues', array(
             'local' => 'id',
             'foreign' => 'product_m2n_product_option_model_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}