<?php

/**
 * Default_Model_Base_ProductGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property integer $product_group_id
 * @property integer $media_image_id
 * @property integer $small_media_image_id
 * @property clob $description
 * @property boolean $show_in_shop
 * @property integer $position
 * @property string $ushort
 * @property string $name
 * @property string $menu_name
 * @property string $title
 * @property string $meta_keywords
 * @property string $meta_title
 * @property string $meta_description
 * @property Default_Model_ProductGroup $ProductGroup
 * @property Default_Model_MediaImage $MediaImage
 * @property Default_Model_MediaImage $SmallMediaImage
 * @property Doctrine_Collection $ProductM2nProductGroup
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_ProductGroup extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('product_group');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('short', 'string', 45, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '45',
             ));
        $this->hasColumn('product_group_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('media_image_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('small_media_image_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => '65535',
             ));
        $this->hasColumn('show_in_shop', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('position', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('ushort', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('menu_name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('meta_keywords', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('meta_title', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));
        $this->hasColumn('meta_description', 'string', 120, array(
             'type' => 'string',
             'length' => '120',
             ));


        $this->index('product_group_id', array(
             'fields' => 
             array(
              0 => 'product_group_id',
             ),
             ));
        $this->index('media_image_id', array(
             'fields' => 
             array(
              0 => 'media_image_id',
             ),
             ));
        $this->index('position_idx', array(
             'fields' => 
             array(
              0 => 'position',
             ),
             ));
        $this->index('small_media_image_id_idx', array(
             'fields' => 
             array(
              0 => 'small_media_image_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_ProductGroup as ProductGroup', array(
             'local' => 'product_group_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_MediaImage as MediaImage', array(
             'local' => 'media_image_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_MediaImage as SmallMediaImage', array(
             'local' => 'small_media_image_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_ProductM2nProductGroup as ProductM2nProductGroup', array(
             'local' => 'id',
             'foreign' => 'product_group_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'product_group_translation',
             'fields' => 
             array(
              0 => 'ushort',
              1 => 'name',
              2 => 'menu_name',
              3 => 'title',
              4 => 'description',
              5 => 'meta_keywords',
              6 => 'meta_title',
              7 => 'meta_description',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}