<?php

/**
 * Default_Model_Base_RegionDatesParticipantsAnswers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $region_date_id
 * @property integer $question_id
 * @property string $answer
 * @property Default_Model_Entity $User
 * @property Default_Model_RegionDates $RegionDate
 * @property Default_Model_DatesQuestions $Question
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_RegionDatesParticipantsAnswers extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('region_dates_participants_answers');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('region_date_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('question_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('answer', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));


        $this->index('user_id_idx', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('region_date_id_idx', array(
             'fields' => 
             array(
              0 => 'region_date_id',
             ),
             ));
        $this->index('question_id_idx', array(
             'fields' => 
             array(
              0 => 'question_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Entity as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_RegionDates as RegionDate', array(
             'local' => 'region_date_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_DatesQuestions as Question', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}