<?php

/**
 * Default_Model_Base_RegionDatesM2nBrand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $region_date_id
 * @property integer $brand_id
 * @property Default_Model_RegionDates $RegionDate
 * @property Default_Model_Brand $Brand
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_RegionDatesM2nBrand extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('region_dates_m2n_brand');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('region_date_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('brand_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));


        $this->index('region_date_id_idx', array(
             'fields' => 
             array(
              0 => 'region_date_id',
             ),
             ));
        $this->index('brand_id_idx', array(
             'fields' => 
             array(
              0 => 'brand_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_RegionDates as RegionDate', array(
             'local' => 'region_date_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Brand as Brand', array(
             'local' => 'brand_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}