<?php

/**
 * Default_Model_Base_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $short
 * @property integer $role_id
 * @property boolean $disabled
 * @property string $default_action_resource
 * @property string $name
 * @property string $description
 * @property Default_Model_Role $Role
 * @property Doctrine_Collection $Entity
 * @property Doctrine_Collection $Action
 * @property Doctrine_Collection $Navigation
 * @property Doctrine_Collection $Media
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_Role extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('role');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('short', 'string', 16, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '16',
             ));
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('default_action_resource', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '120',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasMany('Default_Model_Entity as Entity', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasMany('Default_Model_Action as Action', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasMany('Default_Model_Navigation as Navigation', array(
             'local' => 'short',
             'foreign' => 'role_short'));

        $this->hasMany('Default_Model_Media as Media', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'role_translation',
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}