<?php

/**
 * Default_Model_Base_SurveyAnswers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $survey_id
 * @property integer $entity_id
 * @property clob $survey_answer_data
 * @property Default_Model_Survey $Survey
 * @property Default_Model_Entity $Entity
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_SurveyAnswers extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_answers');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('survey_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('entity_id', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             ));
        $this->hasColumn('survey_answer_data', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));


        $this->index('survey_id_idx', array(
             'fields' => 
             array(
              0 => 'survey_id',
             ),
             ));
        $this->index('entity_id_idx', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Survey as Survey', array(
             'local' => 'survey_id',
             'foreign' => 'id'));

        $this->hasOne('Default_Model_Entity as Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}