<?php

/**
 * Default_Model_Base_Territory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $iso_nr
 * @property integer $territory_iso_nr
 * @property string $name
 * @property Default_Model_Territory $TerritoryIsoNr
 * @property Doctrine_Collection $Territory
 * @property Doctrine_Collection $Country
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
abstract class Default_Model_Base_Territory extends Default_Model_Base_Abstract
{
    public function setTableDefinition()
    {
        $this->setTableName('territory');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('iso_nr', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('territory_iso_nr', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));


        $this->index('territory_iso_nr_idx', array(
             'fields' => 
             array(
              0 => 'territory_iso_nr',
             ),
             ));
        $this->index('iso_nr', array(
             'fields' => 
             array(
              0 => 'iso_nr',
             ),
             ));
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Default_Model_Territory as TerritoryIsoNr', array(
             'local' => 'territory_iso_nr',
             'foreign' => 'iso_nr'));

        $this->hasMany('Default_Model_Territory as Territory', array(
             'local' => 'iso_nr',
             'foreign' => 'territory_iso_nr'));

        $this->hasMany('Default_Model_Country as Country', array(
             'local' => 'iso_nr',
             'foreign' => 'territory_iso_nr'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'tableName' => 'territory_translation',
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $softdelete1 = new Doctrine_Template_SoftDelete();
        $i18n0->addChild($softdelete1);
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}