<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/system/views/scripts/action/update.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: update.phtml 7 2014-03-11 16:18:40Z nm $
 */

echo '<p>' . $this->translate('Using these options may lead to malfunctions. So make sure you really know what you are doing!') . '</p>';

ob_start();
echo '<h3>' . $this->translate('Is real Action?') . '</h3>';
if (count($this->listOfActionMethods) > 0) {
	echo '<ul class="iconized">';
	foreach ($this->listOfActionMethods as $actionModel) {
		echo '<li class="control-play">' . $actionModel->resource . ' <a href="' . $this->url(array('module'=>'system', 'controller'=>'action', 'action'=>'update', 'resource'=>$actionModel->resource, 'do'=>'real-action'), NULL, TRUE) . '">' . $this->translate('Add') . '</a></li>';
	}
	echo '</ul>';
} else {
	echo '<p>' . $this->translate('There is nothing to do.') . '</p>';
}
echo $this->box(ob_get_clean());

ob_start();
echo '<h3>' . $this->translate('Is new Action?') . '</h3>';
if (count($this->listOfNewActions) > 0) {
	echo '<a href="' . $this->url(array('module'=>'system', 'controller'=>'action', 'action'=>'update', 'resource'=>'all', 'do'=>'new-action-all'), NULL, TRUE) . '">' . $this->translate('Add All') . '</a>';
	echo '<ul class="iconized">';
	foreach ($this->listOfNewActions as $actionModel) {
		echo '<li class="control-play">' . $actionModel->resource . ' <a href="' . $this->url(array('module'=>'system', 'controller'=>'action', 'action'=>'update', 'resource'=>$actionModel->resource, 'do'=>'new-action'), NULL, TRUE) . '">' . $this->translate('Add') . '</a></li>';
	}
	echo '</ul>';
} else {
	echo '<p>' . $this->translate('There is nothing to do.') . '</p>';
}
echo $this->box(ob_get_clean());