<?php

/**
 * L8M
 *
 *
 * @filesource /application/views/scripts/assembly/index.phtml
 * @author     Krishna Bhatt <krishna.patel@bcssarl.com>
 * @version    $Id: index.phtml 63 2019-01-07 05:55:59Z nm $
 */
$this->layout()->title = $this->translate('Mitgliederversammlung', 'de');
$this->layout()->headline = $this->translate('Mitgliederversammlung', 'de');
echo $this->protocolListPage($this->assemblyCollection, $this->assemblyPager);