<?php

/**
 * L8M
 *
 *
 * @filesource /application/views/scripts/address-management/create-user.phtml
 * @author     Krishna Bhatt <krishna.patel@bcssarl.com>
 * @version    $Id: create-user.phtml 63 2018-12-06 12:38:40Z nm $
 */
$this->layout()->title = $this->translate(L8M_Acl_CalledFor::action(), 'de');
$this->layout()->headline = $this->translate(L8M_Acl_CalledFor::controller(), 'de') . ' / ' . $this->translate(L8M_Acl_CalledFor::action(), 'de');
echo $this->createForm;