<?php

/**
 * L8M
 *
 *
 * @filesource /application/views/scripts/team/index.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: index.phtml 7 2014-03-11 16:18:40Z nm $
 */

ob_start();
foreach ($this->teamCollection as $teamModel) {

	$imageModel = NULL;
	if ($teamModel->media_image_id) {
		$imageModel = $teamModel->MediaImage->maxBox(320);
	}

	echo '<h3 class="team-name">' . $teamModel->name . '</h3>';
	if ($teamModel->title) {
		echo '<h4 class="team-title">' . $teamModel->title . '</h4>';
	}

	echo '<li class="team-list-item">';
	echo '<div class="team-list-image">' . $imageModel . '</div>';
	echo '<div class="team-list-name">';
	echo $teamModel->name;
	if ($teamModel->title) {
		echo '<span class="team-title">' . $teamModel->title . '</span>';
	}
	if ($this->createTeamDetailLink) {
		echo '<a href="' . $this->url(array('module'=>'default', 'controller'=>'team', 'action'=>'detail', 'name'=>$teamModel->short), NULL, TRUE) . '" class="team-list-link">' . $this->translate('more') . '</a>';
	}
	echo $teamModel->content;
	echo '</div>';
	echo '</li>';
}

$content = ob_get_clean();
if ($content) {
	echo '<ul class="team-list">' . $content . '</ul>';
}