<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/admin/views/scripts/news/create.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: create.phtml 7 2014-03-11 16:18:40Z nm $
 */

if (isset($this->modelForm)) {
	echo $this->modelForm;
}

$this->headScript()->captureStart();
?>

$(document).ready(function() {
	$('li#news_relation_m2n_newsm2ndepartment_selector_link_5_li').click();
	$('a.news_relation_m2n_newsm2ndepartment_add').click();
});

<?php
$this->headScript()->captureEnd();