<?php

/**
 * Default_Model_BackendAdminBoxesActionM2nBackendAdminBoxes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: BackendAdminBoxesActionM2nBackendAdminBoxes.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_BackendAdminBoxesActionM2nBackendAdminBoxes extends Default_Model_Base_BackendAdminBoxesActionM2nBackendAdminBoxes
{

}