<?php

/**
 * Default_Model_Brand
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_Brand extends Default_Model_Base_Brand
{
	/**
	 * get brand details by brand ids.
	 *
	 * @param array $brandIds
	 * @return array result
	 */
	public static function getBrands($brandIds)
	{
		$brandModel = FALSE;
		$count = count($brandIds);
		if (!empty($count)) {
			$brandModel = Doctrine_Query::create()
				->from('Default_Model_Brand')
				->whereIn('id', $brandIds)
				->orderBy('id ASC')
				->execute()
			;
		}

		return $brandModel;
	}
}