<?php

/**
 * Default_Model_ContractType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_ContractType extends Default_Model_Base_ContractType
{
	/**
	 * get contract type details by contract ids.
	 *
	 * @param array $contractTypeIds
	 * @return array result
	 */
	public static function getContractType($contractTypeIds)
	{
		$contractTypeModel = FALSE;
		$count = count($contractTypeIds);
		if (!empty($count)) {
			$contractTypeModel = Doctrine_Query::create()
				->from('Default_Model_ContractType')
				->whereIn('id', $contractTypeIds)
				->orderBy('id ASC')
				->execute()
			;
		}

		return $contractTypeModel;
	}
}