<?php

/**
 * Default_Model_ContentBox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: ContentBox.php 316 2015-04-01 14:03:26Z nm $
 */
class Default_Model_ContentBox extends Default_Model_Base_ContentBox
{

	/**
	 *
	 *
	 * Class Methods
	 *
	 *
	 */

	/**
	 * applies the changes made to this object into database
	 * this method is smart enough to know if any changes are made
	 * and whether to use INSERT or UPDATE statement
	 *
	 * this method also saves the related components
	 *
	 * @param Doctrine_Connection $conn	 optional connection parameter
	 * @throws Exception					if record is not valid and validation is active
	 * @return void
	 */
	public function save(Doctrine_Connection $conn = null)
	{
		$this->_removeResourceFromCache();

		parent::save();

	}

	/**
	 * deletes this data access object and all the related composites
	 * this operation is isolated by a transaction
	 *
	 * this event can be listened by the onPreDelete and onDelete listeners
	 *
	 * @return boolean	  true if successful
	 */
	public function delete(Doctrine_Connection $conn = null)
	{
		$this->_removeResourceFromCache();
		$returnValue = parent::delete($conn);
		return $returnValue;
	}

	/**
	 * remove resource from cache
	 */
	protected function _removeResourceFromCache()
	{

		$cache = L8M_Cache::getCache('PRJ_Cache');
		if ($cache) {
			$cache->remove('tmcecontentbox');
		}
	}
	
}