<?php

/**
 * Default_Model_Department
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_Department extends Default_Model_Base_Department
{
	/**
	 * get department details by department ids.
	 *
	 * @param array $departmentIds
	 * @return array result
	 */
	public static function getDepartment($departmentIds)
	{
		$departmentModel = FALSE;
		$count = count($departmentIds);
		if (!empty($count)) {
			$departmentModel = Doctrine_Query::create()
				->from('Default_Model_Department')
				->whereIn('id', $departmentIds)
				->orderBy('id ASC')
				->execute()
			;
		}

		return $departmentModel;
	}
}