<?php

/**
 * Default_Model_InfoPage
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: InfoPage.php 169 2014-09-02 11:16:55Z nm $
 */
class Default_Model_InfoPage extends Default_Model_Base_InfoPage
{

	/**
	 *
	 *
	 * Class Methods
	 *
	 *
	 */

	/**
	 * deletes this data access object and all the related composites
	 * this operation is isolated by a transaction
	 *
	 * this event can be listened by the onPreDelete and onDelete listeners
	 *
	 * @return boolean	  true if successful
	 */
	public function delete(Doctrine_Connection $conn = null)
	{
		$returnValue = parent::delete($conn);
		PRJ_Sitemap::writeXML();
		return $returnValue;
	}
}