<?php

/**
 * Default_Model_ModelColumnName
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: ModelColumnName.php 322 2015-04-07 13:49:28Z nm $
 */
class Default_Model_ModelColumnName extends Default_Model_Base_ModelColumnName
{

	/**
	 * deletes this data access object and all the related composites
	 * this operation is isolated by a transaction
	 *
	 * this event can be listened by the onPreDelete and onDelete listeners
	 *
	 * @return boolean	  true if successful
	 */
	public function delete(Doctrine_Connection $conn = null)
	{
		if ($this->id &&
			$this->hasRelation('Translation')) {

			$this->_removeTranslationFromCache();
		}
		$this->_removeFieldNameFromCache();

		if ($this->id &&
			class_exists('Default_Model_ModelListImageFolder', TRUE)) {

			$modelListImageFolderCollection = Doctrine_Query::create()
				->from('Default_Model_ModelListImageFolder m')
				->addWhere('m.model_column_name_id = ?', array($this->id))
				->execute()
			;
			foreach ($modelListImageFolderCollection as $modelListImageFolderModel) {
				$modelListImageFolderModel->hardDelete();
			}
		}

		return parent::delete($conn);
	}
}