<?php

/**
 * Default_Model_ModelListColumn
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: ModelListColumn.php 322 2015-04-07 13:49:28Z nm $
 */
class Default_Model_ModelListColumn extends Default_Model_Base_ModelListColumn
{

}