<?php

/**
 * Default_Model_ModelList
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: ModelList.php 321 2015-04-07 13:03:42Z nm $
 */
class Default_Model_ModelList extends Default_Model_Base_ModelList
{

}