<?php

/**
 * Default_Model_ModelMarkedForEditor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: ModelMarkedForEditor.php 37 2014-04-10 13:19:03Z nm $
 */
class Default_Model_ModelMarkedForEditor extends Default_Model_Base_ModelMarkedForEditor
{

}