<?php

/**
 * Default_Model_Module
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Module.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_Module extends Default_Model_Base_Module
{

}