<?php

/**
 * Default_Model_PaymentService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: PaymentService.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_PaymentService extends Default_Model_Base_PaymentService
{

	/**
	 * return charge of shop order
	 *
	 * @param Default_Model_PaymentService $model
	 * @param double $sumPrice
	 */
	public static function getCharge($model, $sumPrice) {

		$returnValue = 0.00;

		if ($model->fixed != NULL &&
			$model->fixed > 0.00) {

			$returnValue += $model->fixed;
		}

		if($model->percent != NULL &&
			$model->percent > 0) {

			$returnValue += $sumPrice / (1 + ($model->percent / 100));

		}

		return $returnValue;

	}

}