<?php

/**
 * Default_Model_Plugin
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Plugin.php 437 2015-09-29 09:14:40Z nm $
 */
class Default_Model_Plugin extends Default_Model_Base_Plugin
{

	/**
	 *
	 *
	 * Class Constants
	 *
	 *
	 */

	/**
	 * The path which files will be uploaded to, relative to BASE_PATH.
	 */
	const UPLOAD_PATH = 'data/temp/plugin';

	/**
	 * Allowed size of plugins.
	 */
	const MAX_UPLOAD_SIZE = 15728640;

	/**
	 *
	 *
	 * Class Methods
	 *
	 *
	 */

	/**
	 * Returns the absolute path in which uploaded files will be stored.
	 *
	 * @return string
	 */
	public static function getUploadPath()
	{
		$uploadPath = BASE_PATH
					. DIRECTORY_SEPARATOR
					. str_replace('/', DIRECTORY_SEPARATOR, self::UPLOAD_PATH)
		;
		return $uploadPath;
	}

	/**
	 * Retrieve max upload size for plugins.
	 *
	 * @return integer
	 */
	public static function getMaxUploadSize()
	{
		$returnValue = self::MAX_UPLOAD_SIZE;
		if (L8M_Library::getMaxUploadSize() < $returnValue) {
			$returnValue = L8M_Library::getMaxUploadSize();
		}

		return $returnValue;
	}
}