<?php

/**
 * Default_Model_ProductM2nTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: ProductM2nTag.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_ProductM2nTag extends Default_Model_Base_ProductM2nTag
{

}