<?php

/**
 * Default_Model_Product
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Product.php 169 2014-09-02 11:16:55Z nm $
 */
class Default_Model_Product extends Default_Model_Base_Product
{

	/**
	 *
	 *
	 * Class Methods
	 *
	 *
	 */


	/**
	 * deletes this data access object and all the related composites
	 * this operation is isolated by a transaction
	 *
	 * this event can be listened by the onPreDelete and onDelete listeners
	 *
	 * @return boolean	  true if successful
	 */
	public function delete(Doctrine_Connection $conn = null)
	{
		$returnValue = parent::delete($conn);
		PRJ_Sitemap::writeXML();
		return $returnValue;

	}

	/**
	 * returns number of days until delivery
	 * @param int $days
	 * @return int
	 */
	public static function calcShipmentReadyDays($days, $orderDate = NULL) {

		$returnValue = NULL;
		$j = -1;

		$k = 0;

		while ($j != 0) {

			$j = 0;

			for($i = $k; $i <= $days; $i++) {

				$timeString = '+' . $i . ' days';
				if ($orderDate == NULL) {
					$timestamp = strtotime($timeString);
				} else {
					$timestamp = strtotime($timeString, $orderDate);
				}
				$dateArray = getdate($timestamp);
				$date = date('Y-m-d', $timestamp);

				$holidayModel = Doctrine_Query::create()
					->from('Default_Model_Holiday h')
					->addWhere('h.date = ?', array($date))
					->limit(1)
					->execute()
					->getFirst()
				;

				if ($dateArray['wday'] == 6 ||
					$dateArray['wday'] == 0 ||
					$holidayModel instanceof Default_Model_Holiday) {

					$j++;
				}

			}

			$k = $days;
			$days += $j;

		}

		$returnValue = $days;

		return $returnValue;

	}

}