<?php

/**
 * Default_Model_ProductInformation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: ProductInformation.php 136 2014-07-10 11:09:57Z nm $
 */
class Default_Model_ProductInformation extends Default_Model_Base_ProductInformation
{

}