<?php

/**
 * Default_Model_Region
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_Region extends Default_Model_Base_Region
{
	/**
	 * get region details by statistics ids.
	 *
	 * @param array $regionIds
	 * @return array result
	 */
	public static function getRegions($regionIds)
	{
		$regionsModel = FALSE;
		$count = count($regionIds);
		if (!empty($count)) {
			$regionsModel = Doctrine_Query::create()
				->from('Default_Model_Region')
				->whereIn('id', $regionIds)
				->orderBy('id ASC')
				->execute()
			;
		}

		return $regionsModel;
	}
}