<?php

/**
 * Default_Model_SiteRights
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Builder.php 5 2014-02-10 10:17:08Z nm $
 */
class Default_Model_SiteRights extends Default_Model_Base_SiteRights
{

}