<?php

/**
 * Default_Model_Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    L8M
 * @subpackage Models (Default Module)
 * @author     Norbert Marks <nm@l8m.com>
 * @version    SVN: $Id: Tag.php 7 2014-03-11 16:18:40Z nm $
 */
class Default_Model_Tag extends Default_Model_Base_Tag
{

}