<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/system/views/scripts/dash-board/index.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: index.phtml 7 2014-03-11 16:18:40Z nm $
 */

$this->layout()->headline = $this->translate('System');
$this->layout()->subheadline = $this->translate('Dash Board');

?>
<p>Aliquam in ligula leo. Suspendisse potenti. Donec lacinia tortor vitae elit scelerisque gravida. Aliquam accumsan tempus adipiscing. In auctor dui et augue semper venenatis. Nunc nec erat vitae diam varius dignissim id ut nunc. Morbi felis purus, tempus sed pellentesque nec, tempor sit amet purus. Etiam faucibus tristique quam vel bibendum. Quisque porta dictum nibh eget viverra. Fusce eget turpis turpis. Integer dapibus nisi sit amet neque placerat lobortis.</p>
<p>Cras elit dolor, fringilla nec cursus eu, porta quis quam. Cras in rhoncus arcu.</p>
<p>Proin gravida magna ut purus porttitor in volutpat nulla luctus. Aenean dictum orci elementum lectus cursus vitae laoreet nunc feugiat. Praesent non auctor urna. Maecenas arcu arcu, viverra non pulvinar at, tincidunt in nisi? In hac habitasse platea dictumst. Phasellus eu euismod diam? Aenean sagittis varius commodo. Integer vehicula pharetra faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis ipsum velit; faucibus in eleifend at; vestibulum nec orci. Nam adipiscing augue eu sem cursus rutrum. Sed mattis venenatis risus ut laoreet. Phasellus nisi libero, pellentesque a tempor pretium, vehicula sit amet est. Donec vestibulum neque ut nunc vehicula bibendum. Quisque luctus egestas nisi, pretium congue purus posuere mattis. Donec id egestas mi. Phasellus semper nibh id dolor fringilla rutrum. Donec nec eros odio, non bibendum elit. Nunc nisl neque, luctus nec molestie sit amet; pulvinar in leo?</p>