<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/system/views/scripts/plugins/edit.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: edit.phtml 5 2014-02-10 10:17:08Z nm $
 */

if (isset($this->modelModelColumn) &&
	isset($this->modelModelName)) {

	$modelName = $this->modelModelColumn . ' <strong>' . $this->modelModelName . '</strong> (ID: ' . $this->modelModelId . ')';
} else {
	$modelName = 'ID: ' . $this->modelModelId;
}

?>
<p><?php echo $this->translate('You are editing')?>: <?php echo $modelName; ?></p>
<?php

if (isset($this->modelForm)) {
	echo $this->modelForm;
}