<?php

/**
* L8M
 *
 *
 * @filesource /application/views/scripts/error/error404.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: error404.phtml 7 2014-03-11 16:18:40Z nm $
 */

$this->layout()->headline = 'HTTP/1.1 404 Nicht gefunden';

/**
 * iconized error list
 */
echo $this->boxError($this->iconizedList('Das angeforderte Dokument konnte nicht gefunden werden.', 'error', 'error last'));