<?php

/**
 * L8M
 *
 *
 * @filesource /application/modules/system/views/scripts/cache/clear.phtml
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: clear.phtml 7 2014-03-11 16:18:40Z nm $
 */

$this->layout()->headline = $this->translate('System');
$this->layout()->subheadline = $this->translate('Cache Clearing requested.');

ob_start();
?>
<p class="last">
	<?php echo vsprintf($this->translate('Cleared %1s entries from cache.'), array($this->cacheClearResult)); ?><br />
	<a href="<?php echo $this->url(array('module'=>'system', 'controller'=>'index', 'action'=>'index'), NULL, TRUE); ?>"><?php echo $this->translate('Back'); ?></a>
</p>
<?php
echo $this->box(ob_get_clean());