<?php

/**
 * L8M
 *
 *
 * @filesource /application/models/Currency/Import.php
 * @author     Norbert Marks <nm@l8m.com>
 * @version    $Id: Import.php 7 2014-03-11 16:18:40Z nm $
 */

/**
 *
 *
 * Default_Model_Currency_Import
 *
 *
 */
class Default_Model_Currency_Import extends L8M_Doctrine_Import_Abstract
{

	/**
	 *
	 *
	 * Class Methods
	 *
	 *
	 */

	/**
	 * Initializes instance.
	 *
	 * @return void
	 */
	protected function _init()
	{
		parent::_init();

		$array = array(
			array('id'=>2,'iso_3'=>'AED','iso_nr'=>784,'name_en'=>'United Arab Emirates dirham','symbol_left'=>'Dhs.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'fils','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'UAE Dirham','sub_name_de'=>null),
			array('id'=>4,'iso_3'=>'ALL','iso_nr'=>8,'name_en'=>'Albanian Lek','symbol_left'=>'L','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'qindarka','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Lek','sub_name_de'=>null),
			array('id'=>5,'iso_3'=>'AMD','iso_nr'=>51,'name_en'=>'Armenian Dram','symbol_left'=>'Dram','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'luma','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Dram','sub_name_de'=>null),
			array('id'=>6,'iso_3'=>'ANG','iso_nr'=>532,'name_en'=>'Netherlands Antillean gulden','symbol_left'=>'NAƒ','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Niederl. Antillen Gulden','sub_name_de'=>null),
			array('id'=>7,'iso_3'=>'AOA','iso_nr'=>973,'name_en'=>'Angolan Kwanza','symbol_left'=>'Kz','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kwanza','sub_name_de'=>null),
			array('id'=>8,'iso_3'=>'ARS','iso_nr'=>32,'name_en'=>'Argentine Peso','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Argentinischer Peso','sub_name_de'=>null),
			array('id'=>9,'iso_3'=>'AUD','iso_nr'=>36,'name_en'=>'Australian Dollar','symbol_left'=>'$A','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Australischer Dollar','sub_name_de'=>null),
			array('id'=>10,'iso_3'=>'AWG','iso_nr'=>533,'name_en'=>'Aruban Guilder','symbol_left'=>'Af.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Aruba Florin','sub_name_de'=>null),
			array('id'=>11,'iso_3'=>'AZN','iso_nr'=>944,'name_en'=>'Azerbaijani Manat','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'qəpik','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>null,'sub_name_de'=>null),
			array('id'=>12,'iso_3'=>'BAM','iso_nr'=>977,'name_en'=>'Bosnia-Herzegovina Convertible Mark','symbol_left'=>'KM','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'feninga','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Konvertierbare Mark','sub_name_de'=>null),
			array('id'=>13,'iso_3'=>'BBD','iso_nr'=>52,'name_en'=>'Barbados Dollar','symbol_left'=>'Bds$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Barbados-Dollar','sub_name_de'=>null),
			array('id'=>14,'iso_3'=>'BDT','iso_nr'=>50,'name_en'=>'Bangladeshi taka','symbol_left'=>'Tk','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'paisa','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Taka','sub_name_de'=>null),
			array('id'=>16,'iso_3'=>'BGN','iso_nr'=>975,'name_en'=>'Bulgarian Lev','symbol_left'=>'lv','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'stotinka','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Lew','sub_name_de'=>null),
			array('id'=>17,'iso_3'=>'BHD','iso_nr'=>48,'name_en'=>'Bahraini Dinar','symbol_left'=>'BD','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>3,'sub_name_en'=>'fils','sub_divisor'=>1000,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Bahrain-Dinar','sub_name_de'=>null),
			array('id'=>18,'iso_3'=>'BIF','iso_nr'=>108,'name_en'=>'Burundi Franc','symbol_left'=>'FBu','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>2,'sub_name_en'=>'centime','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Burundi-Franc','sub_name_de'=>null),
			array('id'=>19,'iso_3'=>'BMD','iso_nr'=>60,'name_en'=>'Bermuda Dollar','symbol_left'=>'BM$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Bermuda-Dollar','sub_name_de'=>null),
			array('id'=>20,'iso_3'=>'BND','iso_nr'=>96,'name_en'=>'Brunei Dollar','symbol_left'=>'B$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'sen','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Brunei-Dollar','sub_name_de'=>null),
			array('id'=>21,'iso_3'=>'BOB','iso_nr'=>68,'name_en'=>'Boliviano','symbol_left'=>'Bs','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Boliviano','sub_name_de'=>null),
			array('id'=>23,'iso_3'=>'BRL','iso_nr'=>986,'name_en'=>'Brazilian Real','symbol_left'=>'R$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Real','sub_name_de'=>null),
			array('id'=>24,'iso_3'=>'BSD','iso_nr'=>44,'name_en'=>'Bahamian Dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Bahama-Dollar','sub_name_de'=>null),
			array('id'=>25,'iso_3'=>'BTN','iso_nr'=>64,'name_en'=>'Bhutanese Ngultrum','symbol_left'=>'Nu','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'chetrum','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Ngultrum','sub_name_de'=>null),
			array('id'=>26,'iso_3'=>'BWP','iso_nr'=>72,'name_en'=>'Botswana pula','symbol_left'=>'P','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'thebe','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Pula','sub_name_de'=>null),
			array('id'=>27,'iso_3'=>'BYR','iso_nr'=>974,'name_en'=>'Belarussian Ruble','symbol_left'=>'Br','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'kapiejka','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Belarus Rubel (neu)','sub_name_de'=>null),
			array('id'=>28,'iso_3'=>'BZD','iso_nr'=>84,'name_en'=>'Belize Dollar','symbol_left'=>'BZ','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Belize-Dollar','sub_name_de'=>null),
			array('id'=>29,'iso_3'=>'CAD','iso_nr'=>124,'name_en'=>'Canadian Dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>'¢','name_de'=>'Kanadischer Dollar','sub_name_de'=>null),
			array('id'=>30,'iso_3'=>'CDF','iso_nr'=>976,'name_en'=>'Congolese franc','symbol_left'=>'FC','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centime','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Franc congolais','sub_name_de'=>null),
			array('id'=>31,'iso_3'=>'CHF','iso_nr'=>756,'name_en'=>'Swiss franc','symbol_left'=>'SFr.','symbol_right'=>null,'thousands_point'=>'\'','decimal_point'=>'.','decimal_digits'=>2,'sub_name_en'=>'centime','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Schweizer Franken','sub_name_de'=>null),
			array('id'=>33,'iso_3'=>'CLP','iso_nr'=>152,'name_en'=>'Chilean Peso','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Chilenischer Peso','sub_name_de'=>null),
			array('id'=>34,'iso_3'=>'CNY','iso_nr'=>156,'name_en'=>'Chinese Yuan Renminbi','symbol_left'=>'Ұ','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'fen','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Renminbi Yuan','sub_name_de'=>null),
			array('id'=>35,'iso_3'=>'COP','iso_nr'=>170,'name_en'=>'Colombian Peso','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kolumbianischer Peso','sub_name_de'=>null),
			array('id'=>36,'iso_3'=>'CRC','iso_nr'=>188,'name_en'=>'Costa Rican colón','symbol_left'=>'₡','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Costa Rica Colon','sub_name_de'=>null),
			array('id'=>37,'iso_3'=>'CUP','iso_nr'=>192,'name_en'=>'Cuban peso','symbol_left'=>'Cub$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kubanischer Peso','sub_name_de'=>null),
			array('id'=>38,'iso_3'=>'CVE','iso_nr'=>132,'name_en'=>'Cape Verde Escudo','symbol_left'=>'CVEsc.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kap Verde Escudo','sub_name_de'=>null),
			array('id'=>39,'iso_3'=>'CYP','iso_nr'=>196,'name_en'=>'Cypriot pound','symbol_left'=>'C£','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Zypern Pfund','sub_name_de'=>null),
			array('id'=>40,'iso_3'=>'CZK','iso_nr'=>203,'name_en'=>'Czech koruna','symbol_left'=>null,'symbol_right'=>'Kč','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'haléř','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tschechische Krone','sub_name_de'=>null),
			array('id'=>41,'iso_3'=>'DJF','iso_nr'=>262,'name_en'=>'Djibouti franc','symbol_left'=>'FD','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Dschibuti-Franc','sub_name_de'=>null),
			array('id'=>42,'iso_3'=>'DKK','iso_nr'=>208,'name_en'=>'Danish krone','symbol_left'=>'kr.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'Øre','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Dänische Krone','sub_name_de'=>null),
			array('id'=>43,'iso_3'=>'DOP','iso_nr'=>214,'name_en'=>'Dominican peso','symbol_left'=>'RD$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Dominikanischer Peso','sub_name_de'=>null),
			array('id'=>44,'iso_3'=>'DZD','iso_nr'=>12,'name_en'=>'Algerian Dinar','symbol_left'=>'DA','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centime','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Algerischer Dinar','sub_name_de'=>null),
			array('id'=>45,'iso_3'=>'EEK','iso_nr'=>233,'name_en'=>'Estonian kroon','symbol_left'=>null,'symbol_right'=>'ekr','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'sent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Estnische Krone','sub_name_de'=>null),
			array('id'=>46,'iso_3'=>'EGP','iso_nr'=>818,'name_en'=>'Egyptian pound','symbol_left'=>'LE','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'piastre','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Ägyptisches Pfund','sub_name_de'=>null),
			array('id'=>47,'iso_3'=>'ERN','iso_nr'=>232,'name_en'=>'Eritrean nakfa','symbol_left'=>'Nfa','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Nakfa','sub_name_de'=>null),
			array('id'=>48,'iso_3'=>'ETB','iso_nr'=>230,'name_en'=>'Ethiopian birr','symbol_left'=>'Br','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'santim','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Birr','sub_name_de'=>null),
			array('id'=>49,'iso_3'=>'EUR','iso_nr'=>978,'name_en'=>'Euro','symbol_left'=>'€','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>'¢','sub_symbol_right'=>null,'name_de'=>'Euro','sub_name_de'=>null),
			array('id'=>50,'iso_3'=>'FJD','iso_nr'=>242,'name_en'=>'Fijian dollar','symbol_left'=>'FJ$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Fidschi Dollar','sub_name_de'=>null),
			array('id'=>51,'iso_3'=>'FKP','iso_nr'=>238,'name_en'=>'Falkland Islands pound','symbol_left'=>'Fl£','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'penny','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Falkland Pfund','sub_name_de'=>null),
			array('id'=>52,'iso_3'=>'GBP','iso_nr'=>826,'name_en'=>'Pound sterling','symbol_left'=>'£','symbol_right'=>null,'thousands_point'=>',','decimal_point'=>'.','decimal_digits'=>2,'sub_name_en'=>'penny','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>'p','name_de'=>'Pfund Sterling','sub_name_de'=>null),
			array('id'=>53,'iso_3'=>'GEL','iso_nr'=>981,'name_en'=>'Georgian lari','symbol_left'=>null,'symbol_right'=>'lari','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'tetri','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Georgischer Lari','sub_name_de'=>null),
			array('id'=>54,'iso_3'=>'GHC','iso_nr'=>288,'name_en'=>'Ghanaian cedi','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'pesewa','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Cedi','sub_name_de'=>null),
			array('id'=>55,'iso_3'=>'GIP','iso_nr'=>292,'name_en'=>'Gibraltar pound','symbol_left'=>'£','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'penny','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Gibraltar Pfund','sub_name_de'=>null),
			array('id'=>56,'iso_3'=>'GMD','iso_nr'=>270,'name_en'=>'Gambian dalasi','symbol_left'=>'D','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'butut','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Dalasi','sub_name_de'=>null),
			array('id'=>57,'iso_3'=>'GNF','iso_nr'=>324,'name_en'=>'Guinea Franc','symbol_left'=>'GF','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Guinea Franc','sub_name_de'=>null),
			array('id'=>58,'iso_3'=>'GTQ','iso_nr'=>320,'name_en'=>'Guatemalan quetzal','symbol_left'=>'Q.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Quetzal','sub_name_de'=>null),
			array('id'=>59,'iso_3'=>'GWP','iso_nr'=>624,'name_en'=>'Guinea-Bissau Peso','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>null,'sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Guinea Bissau Peso','sub_name_de'=>null),
			array('id'=>60,'iso_3'=>'GYD','iso_nr'=>328,'name_en'=>'Guyana Dollar','symbol_left'=>'G$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'Cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Guyana Dollar','sub_name_de'=>null),
			array('id'=>61,'iso_3'=>'HKD','iso_nr'=>344,'name_en'=>'Hong Kong dollar','symbol_left'=>'HK$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Hongkong Dollar','sub_name_de'=>null),
			array('id'=>62,'iso_3'=>'HNL','iso_nr'=>340,'name_en'=>'Honduran lempira','symbol_left'=>'L','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Lempira','sub_name_de'=>null),
			array('id'=>63,'iso_3'=>'HRK','iso_nr'=>191,'name_en'=>'Croatian kuna','symbol_left'=>'kn','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'lipa','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kuna','sub_name_de'=>null),
			array('id'=>64,'iso_3'=>'HTG','iso_nr'=>332,'name_en'=>'Haitian gourde','symbol_left'=>'Gde.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centime','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Gourde','sub_name_de'=>null),
			array('id'=>65,'iso_3'=>'HUF','iso_nr'=>348,'name_en'=>'Hungarian forint','symbol_left'=>null,'symbol_right'=>'Ft','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'fillér','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Forint','sub_name_de'=>null),
			array('id'=>66,'iso_3'=>'IDR','iso_nr'=>360,'name_en'=>'Indonesian rupiah','symbol_left'=>'Rp.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'sen','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Rupiah','sub_name_de'=>null),
			array('id'=>67,'iso_3'=>'ILS','iso_nr'=>376,'name_en'=>'New Israeli Sheqel','symbol_left'=>null,'symbol_right'=>'NIS','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'agora','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Schekel','sub_name_de'=>null),
			array('id'=>68,'iso_3'=>'INR','iso_nr'=>356,'name_en'=>'Indian rupee','symbol_left'=>'Rs','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'paisha','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Indische Rupie','sub_name_de'=>null),
			array('id'=>69,'iso_3'=>'IQD','iso_nr'=>368,'name_en'=>'Iraqi dinar','symbol_left'=>'ID','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>3,'sub_name_en'=>'fils','sub_divisor'=>1000,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Irak Dinar','sub_name_de'=>null),
			array('id'=>70,'iso_3'=>'IRR','iso_nr'=>364,'name_en'=>'Iranian rial','symbol_left'=>'Rls','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'dinar','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Rial','sub_name_de'=>null),
			array('id'=>71,'iso_3'=>'ISK','iso_nr'=>352,'name_en'=>'Icelandic króna','symbol_left'=>null,'symbol_right'=>'ikr','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'aurar','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Isländische Krone','sub_name_de'=>null),
			array('id'=>72,'iso_3'=>'JMD','iso_nr'=>388,'name_en'=>'Jamaican dollar','symbol_left'=>'J$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Jamaika Dollar','sub_name_de'=>null),
			array('id'=>73,'iso_3'=>'JOD','iso_nr'=>400,'name_en'=>'Jordanian dinar','symbol_left'=>'JD','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'piastre','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Jordanischer Dinar','sub_name_de'=>null),
			array('id'=>74,'iso_3'=>'JPY','iso_nr'=>392,'name_en'=>'Japanese yen','symbol_left'=>'¥','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>2,'sub_name_en'=>'sen','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Yen','sub_name_de'=>null),
			array('id'=>75,'iso_3'=>'KES','iso_nr'=>404,'name_en'=>'Kenyan shilling','symbol_left'=>'Kshs.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kenia Schilling','sub_name_de'=>null),
			array('id'=>76,'iso_3'=>'KGS','iso_nr'=>417,'name_en'=>'Kyrgyzstani som','symbol_left'=>'K.S.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'tyiyn','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Som','sub_name_de'=>null),
			array('id'=>77,'iso_3'=>'KHR','iso_nr'=>116,'name_en'=>'Cambodian riel','symbol_left'=>'CR','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'sen','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Riel','sub_name_de'=>null),
			array('id'=>78,'iso_3'=>'KMF','iso_nr'=>174,'name_en'=>'Comorian Franc','symbol_left'=>'CF','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Komoren Franc','sub_name_de'=>null),
			array('id'=>79,'iso_3'=>'KPW','iso_nr'=>408,'name_en'=>'North Korean won','symbol_left'=>'₩n','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'chon','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Nordkoreanischer Won','sub_name_de'=>null),
			array('id'=>80,'iso_3'=>'KRW','iso_nr'=>410,'name_en'=>'South Corean won','symbol_left'=>'￦','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>2,'sub_name_en'=>'jeon','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Südkoreanischer Won','sub_name_de'=>null),
			array('id'=>81,'iso_3'=>'KWD','iso_nr'=>414,'name_en'=>'Kuwaiti dinar','symbol_left'=>'KD','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>3,'sub_name_en'=>'fils','sub_divisor'=>1000,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kuwait Dinar','sub_name_de'=>null),
			array('id'=>82,'iso_3'=>'KYD','iso_nr'=>136,'name_en'=>'Cayman Islands Dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kaiman-Dollar','sub_name_de'=>null),
			array('id'=>83,'iso_3'=>'KZT','iso_nr'=>398,'name_en'=>'Kazakhstani tenge','symbol_left'=>'T','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'tiyin','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tenge','sub_name_de'=>null),
			array('id'=>84,'iso_3'=>'LAK','iso_nr'=>418,'name_en'=>'Lao kip','symbol_left'=>'₭','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'at','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kip','sub_name_de'=>null),
			array('id'=>85,'iso_3'=>'LBP','iso_nr'=>422,'name_en'=>'Lebanese pound','symbol_left'=>null,'symbol_right'=>'LL','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'piastre','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Libanesisches Pfund','sub_name_de'=>null),
			array('id'=>86,'iso_3'=>'LKR','iso_nr'=>144,'name_en'=>'Sri Lankan rupee','symbol_left'=>'Re','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Sri Lanka Rupie','sub_name_de'=>null),
			array('id'=>87,'iso_3'=>'LRD','iso_nr'=>430,'name_en'=>'Liberian dollar','symbol_left'=>'Lib$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Liberianischer Dollar','sub_name_de'=>null),
			array('id'=>88,'iso_3'=>'LSL','iso_nr'=>426,'name_en'=>'Lesotho loti','symbol_left'=>'M','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'sente','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Loti','sub_name_de'=>null),
			array('id'=>89,'iso_3'=>'LTL','iso_nr'=>440,'name_en'=>'Lithuanian litas','symbol_left'=>null,'symbol_right'=>'Lt','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centas','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Litauischer Litas','sub_name_de'=>null),
			array('id'=>90,'iso_3'=>'LVL','iso_nr'=>428,'name_en'=>'Latvian lats','symbol_left'=>'Ls','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'santim','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Lettischer Lats','sub_name_de'=>null),
			array('id'=>91,'iso_3'=>'LYD','iso_nr'=>434,'name_en'=>'Libyan dinar','symbol_left'=>'LD.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>3,'sub_name_en'=>'dirham','sub_divisor'=>1000,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Libyscher Dinar','sub_name_de'=>null),
			array('id'=>92,'iso_3'=>'MAD','iso_nr'=>504,'name_en'=>'Moroccan dirham','symbol_left'=>'Dh','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centime','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Marokkanischer Dirham','sub_name_de'=>null),
			array('id'=>93,'iso_3'=>'MDL','iso_nr'=>498,'name_en'=>'Moldovan leu','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'ban','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Moldau Leu','sub_name_de'=>null),
			array('id'=>95,'iso_3'=>'MKD','iso_nr'=>807,'name_en'=>'Macedonian denar','symbol_left'=>'Den','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'deni','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Denar','sub_name_de'=>null),
			array('id'=>96,'iso_3'=>'MMK','iso_nr'=>104,'name_en'=>'Myanmar kyat','symbol_left'=>'K','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'pya','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kyat','sub_name_de'=>null),
			array('id'=>97,'iso_3'=>'MNT','iso_nr'=>496,'name_en'=>'Mongolian tugrug','symbol_left'=>'₮','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'mongo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tugrik','sub_name_de'=>null),
			array('id'=>98,'iso_3'=>'MOP','iso_nr'=>446,'name_en'=>'Macanese pataca','symbol_left'=>'Pat.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'avo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Pataca','sub_name_de'=>null),
			array('id'=>99,'iso_3'=>'MRO','iso_nr'=>478,'name_en'=>'Mauritanian ouguiya','symbol_left'=>'UM','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'khoum','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Ouguiya','sub_name_de'=>null),
			array('id'=>100,'iso_3'=>'MTL','iso_nr'=>470,'name_en'=>'Maltese lira','symbol_left'=>'Lm','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Maltesische Lira','sub_name_de'=>null),
			array('id'=>101,'iso_3'=>'MUR','iso_nr'=>480,'name_en'=>'Mauritian rupee','symbol_left'=>'Rs','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Mauritius Rupie','sub_name_de'=>null),
			array('id'=>102,'iso_3'=>'MVR','iso_nr'=>462,'name_en'=>'Maldivian rufiyaa','symbol_left'=>'Rf','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'laari','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Rufiyaa','sub_name_de'=>null),
			array('id'=>103,'iso_3'=>'MWK','iso_nr'=>454,'name_en'=>'Malawian kwacha','symbol_left'=>'MK','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'tambala','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Malawi Kwacha','sub_name_de'=>null),
			array('id'=>104,'iso_3'=>'MXN','iso_nr'=>484,'name_en'=>'Mexican peso','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Mexikanischer Peso','sub_name_de'=>null),
			array('id'=>106,'iso_3'=>'MYR','iso_nr'=>458,'name_en'=>'Malaysian ringgit','symbol_left'=>'RM','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'sen','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Malaysischer Ringgit','sub_name_de'=>null),
			array('id'=>107,'iso_3'=>'MZM','iso_nr'=>508,'name_en'=>'Mozambican metical','symbol_left'=>null,'symbol_right'=>'Mt','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Metical','sub_name_de'=>null),
			array('id'=>108,'iso_3'=>'NAD','iso_nr'=>516,'name_en'=>'Namibian dollar','symbol_left'=>'N$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Namibia Dollar','sub_name_de'=>null),
			array('id'=>109,'iso_3'=>'NGN','iso_nr'=>566,'name_en'=>'Nigerian naira','symbol_left'=>'₦','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'kobo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Naira','sub_name_de'=>null),
			array('id'=>110,'iso_3'=>'NIO','iso_nr'=>558,'name_en'=>'Nicaraguan córdoba','symbol_left'=>'C$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Gold-Cordoba','sub_name_de'=>null),
			array('id'=>111,'iso_3'=>'NOK','iso_nr'=>578,'name_en'=>'Norvegian krone','symbol_left'=>'kr','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'øre','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Norwegische Krone','sub_name_de'=>null),
			array('id'=>112,'iso_3'=>'NPR','iso_nr'=>524,'name_en'=>'Nepalese rupee','symbol_left'=>'Rs.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'paisa','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Nepalesische Rupie','sub_name_de'=>null),
			array('id'=>113,'iso_3'=>'NZD','iso_nr'=>554,'name_en'=>'New Zealand dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Neuseeland Dollar','sub_name_de'=>null),
			array('id'=>114,'iso_3'=>'OMR','iso_nr'=>512,'name_en'=>'Omani rial','symbol_left'=>'OR','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>3,'sub_name_en'=>'baiza','sub_divisor'=>1000,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Rial Omani','sub_name_de'=>null),
			array('id'=>115,'iso_3'=>'PAB','iso_nr'=>590,'name_en'=>'Panamanian balboa','symbol_left'=>'B','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centésimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Balboa','sub_name_de'=>null),
			array('id'=>116,'iso_3'=>'PEN','iso_nr'=>604,'name_en'=>'Peruvian nuevo sol','symbol_left'=>'Sl.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Neuer Sol','sub_name_de'=>null),
			array('id'=>117,'iso_3'=>'PGK','iso_nr'=>598,'name_en'=>'Papua New Guinean kina','symbol_left'=>'K','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'toea','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kina','sub_name_de'=>null),
			array('id'=>118,'iso_3'=>'PHP','iso_nr'=>608,'name_en'=>'Philippine peso','symbol_left'=>'P','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Philippinischer Peso','sub_name_de'=>null),
			array('id'=>119,'iso_3'=>'PKR','iso_nr'=>586,'name_en'=>'Pakistani rupee','symbol_left'=>'Rs.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'paisa','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Pakistanische Rupie','sub_name_de'=>null),
			array('id'=>120,'iso_3'=>'PLN','iso_nr'=>985,'name_en'=>'Polish złoty','symbol_left'=>null,'symbol_right'=>'zł','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'grosz','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Zloty','sub_name_de'=>null),
			array('id'=>121,'iso_3'=>'PYG','iso_nr'=>600,'name_en'=>'Paraguayan guaraní','symbol_left'=>'G','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>2,'sub_name_en'=>'centimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Guarani','sub_name_de'=>null),
			array('id'=>122,'iso_3'=>'QAR','iso_nr'=>634,'name_en'=>'Qatari riyal','symbol_left'=>'QR','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'dirham','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Katar Riyal','sub_name_de'=>null),
			array('id'=>123,'iso_3'=>'ROL','iso_nr'=>642,'name_en'=>'Romanian leu','symbol_left'=>null,'symbol_right'=>'l','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'ban','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Leu','sub_name_de'=>null),
			array('id'=>124,'iso_3'=>'RUB','iso_nr'=>643,'name_en'=>'Russian ruble','symbol_left'=>null,'symbol_right'=>'R','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'kopek','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Russischer Rubel (neu)','sub_name_de'=>null),
			array('id'=>126,'iso_3'=>'RWF','iso_nr'=>646,'name_en'=>'Rwandan franc','symbol_left'=>'frw','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>'centime','sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Ruanda Franc','sub_name_de'=>null),
			array('id'=>127,'iso_3'=>'SAR','iso_nr'=>682,'name_en'=>'Saudi riyal','symbol_left'=>'SR','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'hallalah','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Saudi Riyal','sub_name_de'=>null),
			array('id'=>128,'iso_3'=>'SBD','iso_nr'=>90,'name_en'=>'Solomon Islands dollar','symbol_left'=>'SI$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Salomonen Dollar','sub_name_de'=>null),
			array('id'=>129,'iso_3'=>'SCR','iso_nr'=>690,'name_en'=>'Seychelles rupee','symbol_left'=>'SR','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Seychellen Rupie','sub_name_de'=>null),
			array('id'=>130,'iso_3'=>'SDD','iso_nr'=>736,'name_en'=>'Sudanese dinar','symbol_left'=>'sD','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Sudanesischer Dinar','sub_name_de'=>null),
			array('id'=>131,'iso_3'=>'SEK','iso_nr'=>752,'name_en'=>'Swedish krona','symbol_left'=>null,'symbol_right'=>'kr','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'öre','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Schwedische Krone','sub_name_de'=>null),
			array('id'=>132,'iso_3'=>'SGD','iso_nr'=>702,'name_en'=>'Singapore dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Singapur Dollar','sub_name_de'=>null),
			array('id'=>133,'iso_3'=>'SHP','iso_nr'=>654,'name_en'=>'Saint Helena pound','symbol_left'=>'£','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'penny','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'St. Helena Pfund','sub_name_de'=>null),
			array('id'=>134,'iso_3'=>'SIT','iso_nr'=>705,'name_en'=>'Slovenian tolar','symbol_left'=>'SIT','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'stotin','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tolar','sub_name_de'=>null),
			array('id'=>135,'iso_3'=>'SKK','iso_nr'=>703,'name_en'=>'Slovak koruna','symbol_left'=>null,'symbol_right'=>'Sk','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'halier','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>'h','name_de'=>'Slowakische Krone','sub_name_de'=>null),
			array('id'=>136,'iso_3'=>'SLL','iso_nr'=>694,'name_en'=>'Sierra Leonean leone','symbol_left'=>'Le','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Leone','sub_name_de'=>null),
			array('id'=>137,'iso_3'=>'SOS','iso_nr'=>706,'name_en'=>'Somali shilling','symbol_left'=>'So.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centesimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Somalia Schilling','sub_name_de'=>null),
			array('id'=>139,'iso_3'=>'STD','iso_nr'=>678,'name_en'=>'São Tomé and Príncipe dobra','symbol_left'=>'Db','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cêntimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Dobra','sub_name_de'=>null),
			array('id'=>140,'iso_3'=>'SVC','iso_nr'=>222,'name_en'=>'Salvadoran colón','symbol_left'=>'₡','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centavo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'El Salvador Colon','sub_name_de'=>null),
			array('id'=>141,'iso_3'=>'SYP','iso_nr'=>760,'name_en'=>'Syrian pound','symbol_left'=>'£S','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'piastre','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Syrisches Pfund','sub_name_de'=>null),
			array('id'=>142,'iso_3'=>'SZL','iso_nr'=>748,'name_en'=>'Swazi lilangeni','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Lilangeni','sub_name_de'=>null),
			array('id'=>143,'iso_3'=>'THB','iso_nr'=>764,'name_en'=>'Baht','symbol_left'=>null,'symbol_right'=>'Bt','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'satang','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Baht','sub_name_de'=>null),
			array('id'=>144,'iso_3'=>'TJS','iso_nr'=>972,'name_en'=>'Tajikistani somoni','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'diram','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tadschikistan Somoni','sub_name_de'=>null),
			array('id'=>145,'iso_3'=>'TMM','iso_nr'=>795,'name_en'=>'Turkmenistani manat','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'tenge','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Turkmenistan-Manat','sub_name_de'=>null),
			array('id'=>146,'iso_3'=>'TND','iso_nr'=>788,'name_en'=>'Tunisian dinar','symbol_left'=>'TD','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>3,'sub_name_en'=>'millime','sub_divisor'=>1000,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tunesischer Dinar','sub_name_de'=>null),
			array('id'=>147,'iso_3'=>'TOP','iso_nr'=>776,'name_en'=>'Tongan pa\'anga','symbol_left'=>'T$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'seniti','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Paʻanga','sub_name_de'=>null),
			array('id'=>150,'iso_3'=>'TTD','iso_nr'=>780,'name_en'=>'Trinidad and Tobago dollar','symbol_left'=>'TT$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Trinidad und Tobago Dollar','sub_name_de'=>null),
			array('id'=>151,'iso_3'=>'TWD','iso_nr'=>901,'name_en'=>'New Taiwan dollar','symbol_left'=>'NT$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Neuer Taiwan Dollar','sub_name_de'=>null),
			array('id'=>152,'iso_3'=>'TZS','iso_nr'=>834,'name_en'=>'Tanzanian shilling','symbol_left'=>'TSh','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tansania Schilling','sub_name_de'=>null),
			array('id'=>153,'iso_3'=>'UAH','iso_nr'=>980,'name_en'=>'Ukrainian hryvnia','symbol_left'=>'hrn','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'kopiyka','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Hryvnia','sub_name_de'=>null),
			array('id'=>154,'iso_3'=>'UGX','iso_nr'=>800,'name_en'=>'Ugandan shilling','symbol_left'=>'USh','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Uganda Schilling','sub_name_de'=>null),
			array('id'=>155,'iso_3'=>'USD','iso_nr'=>840,'name_en'=>'US dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>',','decimal_point'=>'.','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>'¢','name_de'=>'US Dollar','sub_name_de'=>null),
			array('id'=>156,'iso_3'=>'UYU','iso_nr'=>858,'name_en'=>'Uruguayan peso','symbol_left'=>'UR$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'centésimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Uruguayischer Peso','sub_name_de'=>null),
			array('id'=>157,'iso_3'=>'UZS','iso_nr'=>860,'name_en'=>'Uzbekistani som','symbol_left'=>'U.S.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'tiyin','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Usbekistan Sum','sub_name_de'=>null),
			array('id'=>158,'iso_3'=>'VEB','iso_nr'=>862,'name_en'=>'Bolivar','symbol_left'=>'Bs.','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'céntimo','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Bolivar','sub_name_de'=>null),
			array('id'=>159,'iso_3'=>'VND','iso_nr'=>704,'name_en'=>'Vietnamese đồng','symbol_left'=>null,'symbol_right'=>'₫','thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'xu','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Dong','sub_name_de'=>null),
			array('id'=>160,'iso_3'=>'VUV','iso_nr'=>548,'name_en'=>'Vatu','symbol_left'=>null,'symbol_right'=>'VT','thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>'centime','sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Vatu','sub_name_de'=>null),
			array('id'=>161,'iso_3'=>'WST','iso_nr'=>882,'name_en'=>'Samoan tala','symbol_left'=>'WS$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'sene','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Tala','sub_name_de'=>null),
			array('id'=>162,'iso_3'=>'XAF','iso_nr'=>950,'name_en'=>'CFA Franc BEAC','symbol_left'=>'CFAF','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'CFA Franc (Äquatorial)','sub_name_de'=>null),
			array('id'=>163,'iso_3'=>'XCD','iso_nr'=>951,'name_en'=>'East Caribbean dollar','symbol_left'=>'EC$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Ostkaribischer Dollar','sub_name_de'=>null),
			array('id'=>164,'iso_3'=>'XOF','iso_nr'=>952,'name_en'=>'CFA Franc BCEAO','symbol_left'=>'CFAF','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'CFA Franc (West)','sub_name_de'=>null),
			array('id'=>165,'iso_3'=>'XPF','iso_nr'=>953,'name_en'=>'CFP Franc','symbol_left'=>'CFPF','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>null,'decimal_digits'=>null,'sub_name_en'=>null,'sub_divisor'=>1,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'CFP Franc','sub_name_de'=>null),
			array('id'=>166,'iso_3'=>'YER','iso_nr'=>886,'name_en'=>'Yemeni rial','symbol_left'=>'RI','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'fils','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Jemen Rial','sub_name_de'=>null),
			array('id'=>168,'iso_3'=>'ZAR','iso_nr'=>710,'name_en'=>'South African rand','symbol_left'=>'R','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Rand','sub_name_de'=>null),
			array('id'=>169,'iso_3'=>'ZMK','iso_nr'=>894,'name_en'=>'Zambian kwacha','symbol_left'=>'K','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'ngwee','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Kwacha','sub_name_de'=>null),
			array('id'=>170,'iso_3'=>'ZWD','iso_nr'=>716,'name_en'=>'Zimbabwean dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Simbabwe Dollar','sub_name_de'=>null),
			array('id'=>171,'iso_3'=>'AFN','iso_nr'=>971,'name_en'=>'Afghan afghani','symbol_left'=>'Af','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'pul','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Afghani','sub_name_de'=>null),
			array('id'=>172,'iso_3'=>'CSD','iso_nr'=>891,'name_en'=>'Serbian dinar','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'para','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>null,'sub_name_de'=>null),
			array('id'=>173,'iso_3'=>'MGA','iso_nr'=>969,'name_en'=>'Malagasy ariary','symbol_left'=>null,'symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>1,'sub_name_en'=>'iraimbilanja','sub_divisor'=>5,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Madagaskar Ariary','sub_name_de'=>null),
			array('id'=>174,'iso_3'=>'SRD','iso_nr'=>968,'name_en'=>'Suriname dollar','symbol_left'=>'$','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'cent','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>null,'sub_name_de'=>null),
			array('id'=>175,'iso_3'=>'TRY','iso_nr'=>949,'name_en'=>'Turkish new lira','symbol_left'=>'YTL','symbol_right'=>null,'thousands_point'=>'.','decimal_point'=>',','decimal_digits'=>2,'sub_name_en'=>'new kuruş','sub_divisor'=>100,'sub_symbol_left'=>null,'sub_symbol_right'=>null,'name_de'=>'Neue Türkische Lira','sub_name_de'=>null)
		);

		$this->setArray($array);
	}

	/**
	 * Takes $this->_data and converts it into a Doctrine_Collection
	 *
	 * @return void
	 */
	protected function _generateDataCollection()
	{
		$this->_dataCollection = new Doctrine_Collection($this->getModelClassName());

		foreach($this->_data as $data) {

			$currency = L8M_Doctrine_Record::factory($this->getModelClassName());

			$currency->merge($data);
			$currency->Translation['en']->name = $data['name_en'];
			$currency->Translation['de']->name = $data['name_de'];
			$currency->Translation['en']->sub_name = $data['sub_name_en'];
			$currency->Translation['de']->sub_name = $data['sub_name_de'];

			$this->_dataCollection->add($currency, $data['id']);
		}

	}

}